[2015-04-15 01:53:49] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Router.php:1429 Stack trace: #0 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1050): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 C:\xampp\htdocs\histogram\public\index.php(49): Illuminate\Foundation\Application->run() #5 {main} [] []
[2015-04-15 01:53:51] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Router.php:1429 Stack trace: #0 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1050): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 C:\xampp\htdocs\histogram\public\index.php(49): Illuminate\Foundation\Application->run() #5 {main} [] []
[2015-04-15 02:07:16] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Router.php:1429 Stack trace: #0 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1050): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 C:\xampp\htdocs\histogram\public\index.php(49): Illuminate\Foundation\Application->run() #5 {main} [] []
[2015-04-15 02:07:25] log.ERROR: exception 'Intervention\Image\Exception\MissingDependencyException' with message 'PHP Fileinfo extension must be installed/enabled to use Intervention Image.' in C:\xampp\htdocs\histogram\vendor\intervention\image\src\Intervention\Image\ImageManager.php:123 Stack trace: #0 C:\xampp\htdocs\histogram\vendor\intervention\image\src\Intervention\Image\ImageManager.php(25): Intervention\Image\ImageManager->checkRequirements() #1 C:\xampp\htdocs\histogram\vendor\intervention\image\src\Intervention\Image\ImageServiceProviderLaravel4.php(97): Intervention\Image\ImageManager->__construct(Array) #2 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Container\Container.php(149): Intervention\Image\ImageServiceProviderLaravel4->Intervention\Image\{closure}(Object(Illuminate\Foundation\Application)) #3 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Container\Container.php(305): Illuminate\Container\Container->Illuminate\Container\{closure}(Object(Illuminate\Foundation\Application), Array) #4 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Container\Container.php(250): Illuminate\Container\Container->build(Object(Closure), Array) #5 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(480): Illuminate\Container\Container->make('image', Array) #6 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Container\Container.php(537): Illuminate\Foundation\Application->make('image') #7 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Support\Facades\Facade.php(144): Illuminate\Container\Container->offsetGet('image') #8 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Support\Facades\Facade.php(198): Illuminate\Support\Facades\Facade::resolveFacadeInstance('image') #9 C:\xampp\htdocs\histogram\app\controllers\FilesController.php(106): Illuminate\Support\Facades\Facade::__callStatic('make', Array) #10 C:\xampp\htdocs\histogram\app\controllers\FilesController.php(106): Intervention\Image\Facades\Image::make('C:\\xampp\\htdocs...') #11 [internal function]: FilesController->postUpload() #12 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(138): call_user_func_array(Array, Array) #13 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('postUpload', Array) #14 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Router.php(985): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'postUpload', Array) #15 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}() #16 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Route.php(80): call_user_func_array(Object(Closure), Array) #17 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Route.php(47): Illuminate\Routing\Route->callCallable() #18 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request)) #19 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #20 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #21 C:\xampp\htdocs\histogram\public\index.php(49): Illuminate\Foundation\Application->run() #22 {main} [] []
[2015-04-15 02:07:27] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Router.php:1429 Stack trace: #0 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1050): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 C:\xampp\htdocs\histogram\public\index.php(49): Illuminate\Foundation\Application->run() #5 {main} [] []
[2015-04-15 02:07:29] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Router.php:1429 Stack trace: #0 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1050): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 C:\xampp\htdocs\histogram\public\index.php(49): Illuminate\Foundation\Application->run() #5 {main} [] []
[2015-04-15 02:07:32] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Router.php:1429 Stack trace: #0 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1050): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 C:\xampp\htdocs\histogram\public\index.php(49): Illuminate\Foundation\Application->run() #5 {main} [] []
[2015-04-15 02:57:58] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Router.php:1429 Stack trace: #0 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1050): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 C:\xampp\htdocs\histogram\public\index.php(49): Illuminate\Foundation\Application->run() #5 {main} [] []
[2015-04-15 02:58:08] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Router.php:1429 Stack trace: #0 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1050): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 C:\xampp\htdocs\histogram\public\index.php(49): Illuminate\Foundation\Application->run() #5 {main} [] []
[2015-04-15 02:58:10] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Router.php:1429 Stack trace: #0 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1050): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 C:\xampp\htdocs\histogram\public\index.php(49): Illuminate\Foundation\Application->run() #5 {main} [] []
[2015-04-15 03:10:19] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Router.php:1429 Stack trace: #0 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1050): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 C:\xampp\htdocs\histogram\public\index.php(49): Illuminate\Foundation\Application->run() #5 {main} [] []
[2015-04-15 04:02:00] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Router.php:1429 Stack trace: #0 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1050): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 C:\xampp\htdocs\histogram\public\index.php(49): Illuminate\Foundation\Application->run() #5 {main} [] []
[2015-04-15 13:05:12] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Router.php:1429 Stack trace: #0 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1050): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 C:\xampp\htdocs\histogram\public\index.php(49): Illuminate\Foundation\Application->run() #5 {main} [] []
[2015-04-15 13:05:12] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Router.php:1429 Stack trace: #0 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1050): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 C:\xampp\htdocs\histogram\public\index.php(49): Illuminate\Foundation\Application->run() #5 {main} [] []
[2015-04-15 13:05:22] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Router.php:1429 Stack trace: #0 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1050): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 C:\xampp\htdocs\histogram\public\index.php(49): Illuminate\Foundation\Application->run() #5 {main} [] []
[2015-04-15 13:05:34] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Router.php:1429 Stack trace: #0 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1050): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 C:\xampp\htdocs\histogram\public\index.php(49): Illuminate\Foundation\Application->run() #5 {main} [] []
[2015-04-15 13:05:36] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Router.php:1429 Stack trace: #0 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1050): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 C:\xampp\htdocs\histogram\public\index.php(49): Illuminate\Foundation\Application->run() #5 {main} [] []
[2015-04-15 13:05:48] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Router.php:1429 Stack trace: #0 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1050): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 C:\xampp\htdocs\histogram\public\index.php(49): Illuminate\Foundation\Application->run() #5 {main} [] []
[2015-04-15 13:05:54] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Router.php:1429 Stack trace: #0 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1050): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 C:\xampp\htdocs\histogram\public\index.php(49): Illuminate\Foundation\Application->run() #5 {main} [] []
[2015-04-15 13:06:38] log.ERROR: exception 'Intervention\Image\Exception\MissingDependencyException' with message 'PHP Fileinfo extension must be installed/enabled to use Intervention Image.' in C:\xampp\htdocs\histogram\vendor\intervention\image\src\Intervention\Image\ImageManager.php:123 Stack trace: #0 C:\xampp\htdocs\histogram\vendor\intervention\image\src\Intervention\Image\ImageManager.php(25): Intervention\Image\ImageManager->checkRequirements() #1 C:\xampp\htdocs\histogram\vendor\intervention\image\src\Intervention\Image\ImageServiceProviderLaravel4.php(97): Intervention\Image\ImageManager->__construct(Array) #2 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Container\Container.php(149): Intervention\Image\ImageServiceProviderLaravel4->Intervention\Image\{closure}(Object(Illuminate\Foundation\Application)) #3 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Container\Container.php(305): Illuminate\Container\Container->Illuminate\Container\{closure}(Object(Illuminate\Foundation\Application), Array) #4 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Container\Container.php(250): Illuminate\Container\Container->build(Object(Closure), Array) #5 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(480): Illuminate\Container\Container->make('image', Array) #6 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Container\Container.php(537): Illuminate\Foundation\Application->make('image') #7 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Support\Facades\Facade.php(144): Illuminate\Container\Container->offsetGet('image') #8 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Support\Facades\Facade.php(198): Illuminate\Support\Facades\Facade::resolveFacadeInstance('image') #9 C:\xampp\htdocs\histogram\app\controllers\FilesController.php(106): Illuminate\Support\Facades\Facade::__callStatic('make', Array) #10 C:\xampp\htdocs\histogram\app\controllers\FilesController.php(106): Intervention\Image\Facades\Image::make('C:\\xampp\\htdocs...') #11 [internal function]: FilesController->postUpload() #12 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(138): call_user_func_array(Array, Array) #13 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('postUpload', Array) #14 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Router.php(985): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'postUpload', Array) #15 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}() #16 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Route.php(80): call_user_func_array(Object(Closure), Array) #17 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Route.php(47): Illuminate\Routing\Route->callCallable() #18 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request)) #19 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #20 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #21 C:\xampp\htdocs\histogram\public\index.php(49): Illuminate\Foundation\Application->run() #22 {main} [] []
[2015-04-15 13:06:38] log.ERROR: exception 'Intervention\Image\Exception\MissingDependencyException' with message 'PHP Fileinfo extension must be installed/enabled to use Intervention Image.' in C:\xampp\htdocs\histogram\vendor\intervention\image\src\Intervention\Image\ImageManager.php:123 Stack trace: #0 C:\xampp\htdocs\histogram\vendor\intervention\image\src\Intervention\Image\ImageManager.php(25): Intervention\Image\ImageManager->checkRequirements() #1 C:\xampp\htdocs\histogram\vendor\intervention\image\src\Intervention\Image\ImageServiceProviderLaravel4.php(97): Intervention\Image\ImageManager->__construct(Array) #2 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Container\Container.php(149): Intervention\Image\ImageServiceProviderLaravel4->Intervention\Image\{closure}(Object(Illuminate\Foundation\Application)) #3 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Container\Container.php(305): Illuminate\Container\Container->Illuminate\Container\{closure}(Object(Illuminate\Foundation\Application), Array) #4 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Container\Container.php(250): Illuminate\Container\Container->build(Object(Closure), Array) #5 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(480): Illuminate\Container\Container->make('image', Array) #6 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Container\Container.php(537): Illuminate\Foundation\Application->make('image') #7 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Support\Facades\Facade.php(144): Illuminate\Container\Container->offsetGet('image') #8 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Support\Facades\Facade.php(198): Illuminate\Support\Facades\Facade::resolveFacadeInstance('image') #9 C:\xampp\htdocs\histogram\app\controllers\FilesController.php(106): Illuminate\Support\Facades\Facade::__callStatic('make', Array) #10 C:\xampp\htdocs\histogram\app\controllers\FilesController.php(106): Intervention\Image\Facades\Image::make('C:\\xampp\\htdocs...') #11 [internal function]: FilesController->postUpload() #12 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(138): call_user_func_array(Array, Array) #13 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('postUpload', Array) #14 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Router.php(985): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'postUpload', Array) #15 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}() #16 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Route.php(80): call_user_func_array(Object(Closure), Array) #17 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Route.php(47): Illuminate\Routing\Route->callCallable() #18 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request)) #19 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #20 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #21 C:\xampp\htdocs\histogram\public\index.php(49): Illuminate\Foundation\Application->run() #22 {main} [] []
[2015-04-15 13:06:39] log.ERROR: exception 'Intervention\Image\Exception\MissingDependencyException' with message 'PHP Fileinfo extension must be installed/enabled to use Intervention Image.' in C:\xampp\htdocs\histogram\vendor\intervention\image\src\Intervention\Image\ImageManager.php:123 Stack trace: #0 C:\xampp\htdocs\histogram\vendor\intervention\image\src\Intervention\Image\ImageManager.php(25): Intervention\Image\ImageManager->checkRequirements() #1 C:\xampp\htdocs\histogram\vendor\intervention\image\src\Intervention\Image\ImageServiceProviderLaravel4.php(97): Intervention\Image\ImageManager->__construct(Array) #2 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Container\Container.php(149): Intervention\Image\ImageServiceProviderLaravel4->Intervention\Image\{closure}(Object(Illuminate\Foundation\Application)) #3 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Container\Container.php(305): Illuminate\Container\Container->Illuminate\Container\{closure}(Object(Illuminate\Foundation\Application), Array) #4 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Container\Container.php(250): Illuminate\Container\Container->build(Object(Closure), Array) #5 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(480): Illuminate\Container\Container->make('image', Array) #6 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Container\Container.php(537): Illuminate\Foundation\Application->make('image') #7 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Support\Facades\Facade.php(144): Illuminate\Container\Container->offsetGet('image') #8 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Support\Facades\Facade.php(198): Illuminate\Support\Facades\Facade::resolveFacadeInstance('image') #9 C:\xampp\htdocs\histogram\app\controllers\FilesController.php(106): Illuminate\Support\Facades\Facade::__callStatic('make', Array) #10 C:\xampp\htdocs\histogram\app\controllers\FilesController.php(106): Intervention\Image\Facades\Image::make('C:\\xampp\\htdocs...') #11 [internal function]: FilesController->postUpload() #12 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(138): call_user_func_array(Array, Array) #13 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('postUpload', Array) #14 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Router.php(985): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'postUpload', Array) #15 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}() #16 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Route.php(80): call_user_func_array(Object(Closure), Array) #17 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Route.php(47): Illuminate\Routing\Route->callCallable() #18 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request)) #19 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #20 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #21 C:\xampp\htdocs\histogram\public\index.php(49): Illuminate\Foundation\Application->run() #22 {main} [] []
[2015-04-15 13:06:39] log.ERROR: exception 'Intervention\Image\Exception\MissingDependencyException' with message 'PHP Fileinfo extension must be installed/enabled to use Intervention Image.' in C:\xampp\htdocs\histogram\vendor\intervention\image\src\Intervention\Image\ImageManager.php:123 Stack trace: #0 C:\xampp\htdocs\histogram\vendor\intervention\image\src\Intervention\Image\ImageManager.php(25): Intervention\Image\ImageManager->checkRequirements() #1 C:\xampp\htdocs\histogram\vendor\intervention\image\src\Intervention\Image\ImageServiceProviderLaravel4.php(97): Intervention\Image\ImageManager->__construct(Array) #2 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Container\Container.php(149): Intervention\Image\ImageServiceProviderLaravel4->Intervention\Image\{closure}(Object(Illuminate\Foundation\Application)) #3 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Container\Container.php(305): Illuminate\Container\Container->Illuminate\Container\{closure}(Object(Illuminate\Foundation\Application), Array) #4 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Container\Container.php(250): Illuminate\Container\Container->build(Object(Closure), Array) #5 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(480): Illuminate\Container\Container->make('image', Array) #6 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Container\Container.php(537): Illuminate\Foundation\Application->make('image') #7 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Support\Facades\Facade.php(144): Illuminate\Container\Container->offsetGet('image') #8 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Support\Facades\Facade.php(198): Illuminate\Support\Facades\Facade::resolveFacadeInstance('image') #9 C:\xampp\htdocs\histogram\app\controllers\FilesController.php(106): Illuminate\Support\Facades\Facade::__callStatic('make', Array) #10 C:\xampp\htdocs\histogram\app\controllers\FilesController.php(106): Intervention\Image\Facades\Image::make('C:\\xampp\\htdocs...') #11 [internal function]: FilesController->postUpload() #12 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(138): call_user_func_array(Array, Array) #13 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('postUpload', Array) #14 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Router.php(985): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'postUpload', Array) #15 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}() #16 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Route.php(80): call_user_func_array(Object(Closure), Array) #17 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Route.php(47): Illuminate\Routing\Route->callCallable() #18 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request)) #19 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #20 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #21 C:\xampp\htdocs\histogram\public\index.php(49): Illuminate\Foundation\Application->run() #22 {main} [] []
[2015-04-15 13:06:39] log.ERROR: exception 'Intervention\Image\Exception\MissingDependencyException' with message 'PHP Fileinfo extension must be installed/enabled to use Intervention Image.' in C:\xampp\htdocs\histogram\vendor\intervention\image\src\Intervention\Image\ImageManager.php:123 Stack trace: #0 C:\xampp\htdocs\histogram\vendor\intervention\image\src\Intervention\Image\ImageManager.php(25): Intervention\Image\ImageManager->checkRequirements() #1 C:\xampp\htdocs\histogram\vendor\intervention\image\src\Intervention\Image\ImageServiceProviderLaravel4.php(97): Intervention\Image\ImageManager->__construct(Array) #2 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Container\Container.php(149): Intervention\Image\ImageServiceProviderLaravel4->Intervention\Image\{closure}(Object(Illuminate\Foundation\Application)) #3 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Container\Container.php(305): Illuminate\Container\Container->Illuminate\Container\{closure}(Object(Illuminate\Foundation\Application), Array) #4 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Container\Container.php(250): Illuminate\Container\Container->build(Object(Closure), Array) #5 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(480): Illuminate\Container\Container->make('image', Array) #6 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Container\Container.php(537): Illuminate\Foundation\Application->make('image') #7 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Support\Facades\Facade.php(144): Illuminate\Container\Container->offsetGet('image') #8 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Support\Facades\Facade.php(198): Illuminate\Support\Facades\Facade::resolveFacadeInstance('image') #9 C:\xampp\htdocs\histogram\app\controllers\FilesController.php(106): Illuminate\Support\Facades\Facade::__callStatic('make', Array) #10 C:\xampp\htdocs\histogram\app\controllers\FilesController.php(106): Intervention\Image\Facades\Image::make('C:\\xampp\\htdocs...') #11 [internal function]: FilesController->postUpload() #12 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(138): call_user_func_array(Array, Array) #13 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('postUpload', Array) #14 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Router.php(985): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'postUpload', Array) #15 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}() #16 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Route.php(80): call_user_func_array(Object(Closure), Array) #17 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Route.php(47): Illuminate\Routing\Route->callCallable() #18 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request)) #19 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #20 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #21 C:\xampp\htdocs\histogram\public\index.php(49): Illuminate\Foundation\Application->run() #22 {main} [] []
[2015-04-15 13:06:39] log.ERROR: exception 'Intervention\Image\Exception\MissingDependencyException' with message 'PHP Fileinfo extension must be installed/enabled to use Intervention Image.' in C:\xampp\htdocs\histogram\vendor\intervention\image\src\Intervention\Image\ImageManager.php:123 Stack trace: #0 C:\xampp\htdocs\histogram\vendor\intervention\image\src\Intervention\Image\ImageManager.php(25): Intervention\Image\ImageManager->checkRequirements() #1 C:\xampp\htdocs\histogram\vendor\intervention\image\src\Intervention\Image\ImageServiceProviderLaravel4.php(97): Intervention\Image\ImageManager->__construct(Array) #2 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Container\Container.php(149): Intervention\Image\ImageServiceProviderLaravel4->Intervention\Image\{closure}(Object(Illuminate\Foundation\Application)) #3 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Container\Container.php(305): Illuminate\Container\Container->Illuminate\Container\{closure}(Object(Illuminate\Foundation\Application), Array) #4 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Container\Container.php(250): Illuminate\Container\Container->build(Object(Closure), Array) #5 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(480): Illuminate\Container\Container->make('image', Array) #6 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Container\Container.php(537): Illuminate\Foundation\Application->make('image') #7 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Support\Facades\Facade.php(144): Illuminate\Container\Container->offsetGet('image') #8 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Support\Facades\Facade.php(198): Illuminate\Support\Facades\Facade::resolveFacadeInstance('image') #9 C:\xampp\htdocs\histogram\app\controllers\FilesController.php(106): Illuminate\Support\Facades\Facade::__callStatic('make', Array) #10 C:\xampp\htdocs\histogram\app\controllers\FilesController.php(106): Intervention\Image\Facades\Image::make('C:\\xampp\\htdocs...') #11 [internal function]: FilesController->postUpload() #12 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(138): call_user_func_array(Array, Array) #13 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('postUpload', Array) #14 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Router.php(985): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'postUpload', Array) #15 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}() #16 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Route.php(80): call_user_func_array(Object(Closure), Array) #17 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Route.php(47): Illuminate\Routing\Route->callCallable() #18 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request)) #19 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #20 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #21 C:\xampp\htdocs\histogram\public\index.php(49): Illuminate\Foundation\Application->run() #22 {main} [] []
[2015-04-15 13:06:42] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Router.php:1429 Stack trace: #0 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1050): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 C:\xampp\htdocs\histogram\public\index.php(49): Illuminate\Foundation\Application->run() #5 {main} [] []
[2015-04-15 13:06:46] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Router.php:1429 Stack trace: #0 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1050): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 C:\xampp\htdocs\histogram\public\index.php(49): Illuminate\Foundation\Application->run() #5 {main} [] []
[2015-04-15 13:08:10] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Router.php:1429 Stack trace: #0 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1050): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 C:\xampp\htdocs\histogram\public\index.php(49): Illuminate\Foundation\Application->run() #5 {main} [] []
[2015-04-15 13:19:28] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Router.php:1429 Stack trace: #0 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1050): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 C:\xampp\htdocs\histogram\public\index.php(49): Illuminate\Foundation\Application->run() #5 {main} [] []
[2015-04-15 13:19:30] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Router.php:1429 Stack trace: #0 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1050): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 C:\xampp\htdocs\histogram\public\index.php(49): Illuminate\Foundation\Application->run() #5 {main} [] []
[2015-04-15 13:19:38] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Router.php:1429 Stack trace: #0 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1050): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 C:\xampp\htdocs\histogram\public\index.php(49): Illuminate\Foundation\Application->run() #5 {main} [] []
[2015-04-15 13:19:52] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Router.php:1429 Stack trace: #0 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1050): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 C:\xampp\htdocs\histogram\public\index.php(49): Illuminate\Foundation\Application->run() #5 {main} [] []
[2015-04-15 13:20:13] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Router.php:1429 Stack trace: #0 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1050): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 C:\xampp\htdocs\histogram\public\index.php(49): Illuminate\Foundation\Application->run() #5 {main} [] []
[2015-04-15 13:21:07] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Router.php:1429 Stack trace: #0 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1050): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 C:\xampp\htdocs\histogram\public\index.php(49): Illuminate\Foundation\Application->run() #5 {main} [] []
[2015-04-15 13:21:46] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Router.php:1429 Stack trace: #0 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1050): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 C:\xampp\htdocs\histogram\public\index.php(49): Illuminate\Foundation\Application->run() #5 {main} [] []
[2015-04-15 13:21:52] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Router.php:1429 Stack trace: #0 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1050): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 C:\xampp\htdocs\histogram\public\index.php(49): Illuminate\Foundation\Application->run() #5 {main} [] []
[2015-04-15 13:21:57] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Router.php:1429 Stack trace: #0 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1050): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 C:\xampp\htdocs\histogram\public\index.php(49): Illuminate\Foundation\Application->run() #5 {main} [] []
[2015-04-15 13:22:05] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Router.php:1429 Stack trace: #0 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1050): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 C:\xampp\htdocs\histogram\public\index.php(49): Illuminate\Foundation\Application->run() #5 {main} [] []
[2015-04-15 13:22:12] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Router.php:1429 Stack trace: #0 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1050): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 C:\xampp\htdocs\histogram\public\index.php(49): Illuminate\Foundation\Application->run() #5 {main} [] []
[2015-04-15 13:22:52] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Router.php:1429 Stack trace: #0 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1050): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 C:\xampp\htdocs\histogram\public\index.php(49): Illuminate\Foundation\Application->run() #5 {main} [] []
[2015-04-15 13:22:59] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Router.php:1429 Stack trace: #0 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1050): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 C:\xampp\htdocs\histogram\public\index.php(49): Illuminate\Foundation\Application->run() #5 {main} [] []
[2015-04-15 13:23:06] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Router.php:1429 Stack trace: #0 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1050): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 C:\xampp\htdocs\histogram\public\index.php(49): Illuminate\Foundation\Application->run() #5 {main} [] []
[2015-04-15 13:23:11] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Router.php:1429 Stack trace: #0 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1050): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 C:\xampp\htdocs\histogram\public\index.php(49): Illuminate\Foundation\Application->run() #5 {main} [] []
[2015-04-15 13:23:14] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Router.php:1429 Stack trace: #0 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1050): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 C:\xampp\htdocs\histogram\public\index.php(49): Illuminate\Foundation\Application->run() #5 {main} [] []
[2015-04-15 13:23:22] log.ERROR: exception 'Intervention\Image\Exception\MissingDependencyException' with message 'PHP Fileinfo extension must be installed/enabled to use Intervention Image.' in C:\xampp\htdocs\histogram\vendor\intervention\image\src\Intervention\Image\ImageManager.php:123 Stack trace: #0 C:\xampp\htdocs\histogram\vendor\intervention\image\src\Intervention\Image\ImageManager.php(25): Intervention\Image\ImageManager->checkRequirements() #1 C:\xampp\htdocs\histogram\vendor\intervention\image\src\Intervention\Image\ImageServiceProviderLaravel4.php(97): Intervention\Image\ImageManager->__construct(Array) #2 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Container\Container.php(149): Intervention\Image\ImageServiceProviderLaravel4->Intervention\Image\{closure}(Object(Illuminate\Foundation\Application)) #3 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Container\Container.php(305): Illuminate\Container\Container->Illuminate\Container\{closure}(Object(Illuminate\Foundation\Application), Array) #4 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Container\Container.php(250): Illuminate\Container\Container->build(Object(Closure), Array) #5 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(480): Illuminate\Container\Container->make('image', Array) #6 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Container\Container.php(537): Illuminate\Foundation\Application->make('image') #7 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Support\Facades\Facade.php(144): Illuminate\Container\Container->offsetGet('image') #8 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Support\Facades\Facade.php(198): Illuminate\Support\Facades\Facade::resolveFacadeInstance('image') #9 C:\xampp\htdocs\histogram\app\controllers\FilesController.php(106): Illuminate\Support\Facades\Facade::__callStatic('make', Array) #10 C:\xampp\htdocs\histogram\app\controllers\FilesController.php(106): Intervention\Image\Facades\Image::make('C:\\xampp\\htdocs...') #11 [internal function]: FilesController->postUpload() #12 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(138): call_user_func_array(Array, Array) #13 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('postUpload', Array) #14 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Router.php(985): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'postUpload', Array) #15 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}() #16 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Route.php(80): call_user_func_array(Object(Closure), Array) #17 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Route.php(47): Illuminate\Routing\Route->callCallable() #18 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request)) #19 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #20 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #21 C:\xampp\htdocs\histogram\public\index.php(49): Illuminate\Foundation\Application->run() #22 {main} [] []
[2015-04-15 13:23:22] log.ERROR: exception 'Intervention\Image\Exception\MissingDependencyException' with message 'PHP Fileinfo extension must be installed/enabled to use Intervention Image.' in C:\xampp\htdocs\histogram\vendor\intervention\image\src\Intervention\Image\ImageManager.php:123 Stack trace: #0 C:\xampp\htdocs\histogram\vendor\intervention\image\src\Intervention\Image\ImageManager.php(25): Intervention\Image\ImageManager->checkRequirements() #1 C:\xampp\htdocs\histogram\vendor\intervention\image\src\Intervention\Image\ImageServiceProviderLaravel4.php(97): Intervention\Image\ImageManager->__construct(Array) #2 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Container\Container.php(149): Intervention\Image\ImageServiceProviderLaravel4->Intervention\Image\{closure}(Object(Illuminate\Foundation\Application)) #3 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Container\Container.php(305): Illuminate\Container\Container->Illuminate\Container\{closure}(Object(Illuminate\Foundation\Application), Array) #4 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Container\Container.php(250): Illuminate\Container\Container->build(Object(Closure), Array) #5 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(480): Illuminate\Container\Container->make('image', Array) #6 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Container\Container.php(537): Illuminate\Foundation\Application->make('image') #7 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Support\Facades\Facade.php(144): Illuminate\Container\Container->offsetGet('image') #8 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Support\Facades\Facade.php(198): Illuminate\Support\Facades\Facade::resolveFacadeInstance('image') #9 C:\xampp\htdocs\histogram\app\controllers\FilesController.php(106): Illuminate\Support\Facades\Facade::__callStatic('make', Array) #10 C:\xampp\htdocs\histogram\app\controllers\FilesController.php(106): Intervention\Image\Facades\Image::make('C:\\xampp\\htdocs...') #11 [internal function]: FilesController->postUpload() #12 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(138): call_user_func_array(Array, Array) #13 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('postUpload', Array) #14 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Router.php(985): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'postUpload', Array) #15 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}() #16 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Route.php(80): call_user_func_array(Object(Closure), Array) #17 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Route.php(47): Illuminate\Routing\Route->callCallable() #18 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request)) #19 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #20 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #21 C:\xampp\htdocs\histogram\public\index.php(49): Illuminate\Foundation\Application->run() #22 {main} [] []
[2015-04-15 13:23:23] log.ERROR: exception 'Intervention\Image\Exception\MissingDependencyException' with message 'PHP Fileinfo extension must be installed/enabled to use Intervention Image.' in C:\xampp\htdocs\histogram\vendor\intervention\image\src\Intervention\Image\ImageManager.php:123 Stack trace: #0 C:\xampp\htdocs\histogram\vendor\intervention\image\src\Intervention\Image\ImageManager.php(25): Intervention\Image\ImageManager->checkRequirements() #1 C:\xampp\htdocs\histogram\vendor\intervention\image\src\Intervention\Image\ImageServiceProviderLaravel4.php(97): Intervention\Image\ImageManager->__construct(Array) #2 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Container\Container.php(149): Intervention\Image\ImageServiceProviderLaravel4->Intervention\Image\{closure}(Object(Illuminate\Foundation\Application)) #3 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Container\Container.php(305): Illuminate\Container\Container->Illuminate\Container\{closure}(Object(Illuminate\Foundation\Application), Array) #4 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Container\Container.php(250): Illuminate\Container\Container->build(Object(Closure), Array) #5 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(480): Illuminate\Container\Container->make('image', Array) #6 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Container\Container.php(537): Illuminate\Foundation\Application->make('image') #7 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Support\Facades\Facade.php(144): Illuminate\Container\Container->offsetGet('image') #8 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Support\Facades\Facade.php(198): Illuminate\Support\Facades\Facade::resolveFacadeInstance('image') #9 C:\xampp\htdocs\histogram\app\controllers\FilesController.php(106): Illuminate\Support\Facades\Facade::__callStatic('make', Array) #10 C:\xampp\htdocs\histogram\app\controllers\FilesController.php(106): Intervention\Image\Facades\Image::make('C:\\xampp\\htdocs...') #11 [internal function]: FilesController->postUpload() #12 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(138): call_user_func_array(Array, Array) #13 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('postUpload', Array) #14 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Router.php(985): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'postUpload', Array) #15 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}() #16 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Route.php(80): call_user_func_array(Object(Closure), Array) #17 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Route.php(47): Illuminate\Routing\Route->callCallable() #18 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request)) #19 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #20 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #21 C:\xampp\htdocs\histogram\public\index.php(49): Illuminate\Foundation\Application->run() #22 {main} [] []
[2015-04-15 13:23:23] log.ERROR: exception 'Intervention\Image\Exception\MissingDependencyException' with message 'PHP Fileinfo extension must be installed/enabled to use Intervention Image.' in C:\xampp\htdocs\histogram\vendor\intervention\image\src\Intervention\Image\ImageManager.php:123 Stack trace: #0 C:\xampp\htdocs\histogram\vendor\intervention\image\src\Intervention\Image\ImageManager.php(25): Intervention\Image\ImageManager->checkRequirements() #1 C:\xampp\htdocs\histogram\vendor\intervention\image\src\Intervention\Image\ImageServiceProviderLaravel4.php(97): Intervention\Image\ImageManager->__construct(Array) #2 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Container\Container.php(149): Intervention\Image\ImageServiceProviderLaravel4->Intervention\Image\{closure}(Object(Illuminate\Foundation\Application)) #3 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Container\Container.php(305): Illuminate\Container\Container->Illuminate\Container\{closure}(Object(Illuminate\Foundation\Application), Array) #4 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Container\Container.php(250): Illuminate\Container\Container->build(Object(Closure), Array) #5 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(480): Illuminate\Container\Container->make('image', Array) #6 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Container\Container.php(537): Illuminate\Foundation\Application->make('image') #7 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Support\Facades\Facade.php(144): Illuminate\Container\Container->offsetGet('image') #8 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Support\Facades\Facade.php(198): Illuminate\Support\Facades\Facade::resolveFacadeInstance('image') #9 C:\xampp\htdocs\histogram\app\controllers\FilesController.php(106): Illuminate\Support\Facades\Facade::__callStatic('make', Array) #10 C:\xampp\htdocs\histogram\app\controllers\FilesController.php(106): Intervention\Image\Facades\Image::make('C:\\xampp\\htdocs...') #11 [internal function]: FilesController->postUpload() #12 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(138): call_user_func_array(Array, Array) #13 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('postUpload', Array) #14 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Router.php(985): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'postUpload', Array) #15 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}() #16 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Route.php(80): call_user_func_array(Object(Closure), Array) #17 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Route.php(47): Illuminate\Routing\Route->callCallable() #18 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request)) #19 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #20 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #21 C:\xampp\htdocs\histogram\public\index.php(49): Illuminate\Foundation\Application->run() #22 {main} [] []
[2015-04-15 13:23:23] log.ERROR: exception 'Intervention\Image\Exception\MissingDependencyException' with message 'PHP Fileinfo extension must be installed/enabled to use Intervention Image.' in C:\xampp\htdocs\histogram\vendor\intervention\image\src\Intervention\Image\ImageManager.php:123 Stack trace: #0 C:\xampp\htdocs\histogram\vendor\intervention\image\src\Intervention\Image\ImageManager.php(25): Intervention\Image\ImageManager->checkRequirements() #1 C:\xampp\htdocs\histogram\vendor\intervention\image\src\Intervention\Image\ImageServiceProviderLaravel4.php(97): Intervention\Image\ImageManager->__construct(Array) #2 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Container\Container.php(149): Intervention\Image\ImageServiceProviderLaravel4->Intervention\Image\{closure}(Object(Illuminate\Foundation\Application)) #3 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Container\Container.php(305): Illuminate\Container\Container->Illuminate\Container\{closure}(Object(Illuminate\Foundation\Application), Array) #4 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Container\Container.php(250): Illuminate\Container\Container->build(Object(Closure), Array) #5 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(480): Illuminate\Container\Container->make('image', Array) #6 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Container\Container.php(537): Illuminate\Foundation\Application->make('image') #7 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Support\Facades\Facade.php(144): Illuminate\Container\Container->offsetGet('image') #8 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Support\Facades\Facade.php(198): Illuminate\Support\Facades\Facade::resolveFacadeInstance('image') #9 C:\xampp\htdocs\histogram\app\controllers\FilesController.php(106): Illuminate\Support\Facades\Facade::__callStatic('make', Array) #10 C:\xampp\htdocs\histogram\app\controllers\FilesController.php(106): Intervention\Image\Facades\Image::make('C:\\xampp\\htdocs...') #11 [internal function]: FilesController->postUpload() #12 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(138): call_user_func_array(Array, Array) #13 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('postUpload', Array) #14 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Router.php(985): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'postUpload', Array) #15 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}() #16 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Route.php(80): call_user_func_array(Object(Closure), Array) #17 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Route.php(47): Illuminate\Routing\Route->callCallable() #18 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request)) #19 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #20 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #21 C:\xampp\htdocs\histogram\public\index.php(49): Illuminate\Foundation\Application->run() #22 {main} [] []
[2015-04-15 13:23:23] log.ERROR: exception 'Intervention\Image\Exception\MissingDependencyException' with message 'PHP Fileinfo extension must be installed/enabled to use Intervention Image.' in C:\xampp\htdocs\histogram\vendor\intervention\image\src\Intervention\Image\ImageManager.php:123 Stack trace: #0 C:\xampp\htdocs\histogram\vendor\intervention\image\src\Intervention\Image\ImageManager.php(25): Intervention\Image\ImageManager->checkRequirements() #1 C:\xampp\htdocs\histogram\vendor\intervention\image\src\Intervention\Image\ImageServiceProviderLaravel4.php(97): Intervention\Image\ImageManager->__construct(Array) #2 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Container\Container.php(149): Intervention\Image\ImageServiceProviderLaravel4->Intervention\Image\{closure}(Object(Illuminate\Foundation\Application)) #3 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Container\Container.php(305): Illuminate\Container\Container->Illuminate\Container\{closure}(Object(Illuminate\Foundation\Application), Array) #4 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Container\Container.php(250): Illuminate\Container\Container->build(Object(Closure), Array) #5 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(480): Illuminate\Container\Container->make('image', Array) #6 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Container\Container.php(537): Illuminate\Foundation\Application->make('image') #7 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Support\Facades\Facade.php(144): Illuminate\Container\Container->offsetGet('image') #8 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Support\Facades\Facade.php(198): Illuminate\Support\Facades\Facade::resolveFacadeInstance('image') #9 C:\xampp\htdocs\histogram\app\controllers\FilesController.php(106): Illuminate\Support\Facades\Facade::__callStatic('make', Array) #10 C:\xampp\htdocs\histogram\app\controllers\FilesController.php(106): Intervention\Image\Facades\Image::make('C:\\xampp\\htdocs...') #11 [internal function]: FilesController->postUpload() #12 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(138): call_user_func_array(Array, Array) #13 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('postUpload', Array) #14 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Router.php(985): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'postUpload', Array) #15 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}() #16 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Route.php(80): call_user_func_array(Object(Closure), Array) #17 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Route.php(47): Illuminate\Routing\Route->callCallable() #18 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request)) #19 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #20 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #21 C:\xampp\htdocs\histogram\public\index.php(49): Illuminate\Foundation\Application->run() #22 {main} [] []
[2015-04-15 13:23:34] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Router.php:1429 Stack trace: #0 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1050): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 C:\xampp\htdocs\histogram\public\index.php(49): Illuminate\Foundation\Application->run() #5 {main} [] []
[2015-04-15 13:23:36] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Router.php:1429 Stack trace: #0 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1050): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 C:\xampp\htdocs\histogram\public\index.php(49): Illuminate\Foundation\Application->run() #5 {main} [] []
[2015-04-15 13:24:24] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Router.php:1429 Stack trace: #0 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1050): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 C:\xampp\htdocs\histogram\public\index.php(49): Illuminate\Foundation\Application->run() #5 {main} [] []
[2015-04-15 13:25:18] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Router.php:1429 Stack trace: #0 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1050): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 C:\xampp\htdocs\histogram\public\index.php(49): Illuminate\Foundation\Application->run() #5 {main} [] []
[2015-04-15 13:25:32] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Router.php:1429 Stack trace: #0 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1050): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 C:\xampp\htdocs\histogram\public\index.php(49): Illuminate\Foundation\Application->run() #5 {main} [] []
[2015-04-15 13:25:41] log.ERROR: exception 'ErrorException' with message 'unlink(C:\xampp\htdocs\histogram\public//charts/2015-03-26/887-150326065635.png): No such file or directory' in C:\xampp\htdocs\histogram\app\controllers\AutomateController.php:212 Stack trace: #0 [internal function]: Illuminate\Exception\Handler->handleError(2, 'unlink(C:\\xampp...', 'C:\\xampp\\htdocs...', 212, Array) #1 C:\xampp\htdocs\histogram\app\controllers\AutomateController.php(212): unlink('C:\\xampp\\htdocs...') #2 [internal function]: AutomateController->getDestroy() #3 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(138): call_user_func_array(Array, Array) #4 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('getDestroy', Array) #5 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Router.php(985): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'getDestroy', Array) #6 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}() #7 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Route.php(80): call_user_func_array(Object(Closure), Array) #8 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Route.php(47): Illuminate\Routing\Route->callCallable() #9 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request)) #10 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #11 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #12 C:\xampp\htdocs\histogram\public\index.php(49): Illuminate\Foundation\Application->run() #13 {main} [] []
[2015-04-15 13:25:55] log.ERROR: exception 'ErrorException' with message 'Trying to get property of non-object' in C:\xampp\htdocs\histogram\app\controllers\AutomateController.php:214 Stack trace: #0 C:\xampp\htdocs\histogram\app\controllers\AutomateController.php(214): Illuminate\Exception\Handler->handleError(8, 'Trying to get p...', 'C:\\xampp\\htdocs...', 214, Array) #1 [internal function]: AutomateController->getDestroy() #2 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(138): call_user_func_array(Array, Array) #3 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('getDestroy', Array) #4 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Router.php(985): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'getDestroy', Array) #5 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}() #6 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Route.php(80): call_user_func_array(Object(Closure), Array) #7 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Route.php(47): Illuminate\Routing\Route->callCallable() #8 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request)) #9 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #10 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #11 C:\xampp\htdocs\histogram\public\index.php(49): Illuminate\Foundation\Application->run() #12 {main} [] []
[2015-04-15 13:28:19] log.ERROR: exception 'ErrorException' with message 'Trying to get property of non-object' in C:\xampp\htdocs\histogram\app\controllers\AutomateController.php:214 Stack trace: #0 C:\xampp\htdocs\histogram\app\controllers\AutomateController.php(214): Illuminate\Exception\Handler->handleError(8, 'Trying to get p...', 'C:\\xampp\\htdocs...', 214, Array) #1 [internal function]: AutomateController->getDestroy() #2 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(138): call_user_func_array(Array, Array) #3 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('getDestroy', Array) #4 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Router.php(985): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'getDestroy', Array) #5 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}() #6 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Route.php(80): call_user_func_array(Object(Closure), Array) #7 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Route.php(47): Illuminate\Routing\Route->callCallable() #8 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request)) #9 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #10 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #11 C:\xampp\htdocs\histogram\public\index.php(49): Illuminate\Foundation\Application->run() #12 {main} [] []
[2015-04-15 13:28:29] log.ERROR: exception 'ErrorException' with message 'Trying to get property of non-object' in C:\xampp\htdocs\histogram\app\controllers\AutomateController.php:214 Stack trace: #0 C:\xampp\htdocs\histogram\app\controllers\AutomateController.php(214): Illuminate\Exception\Handler->handleError(8, 'Trying to get p...', 'C:\\xampp\\htdocs...', 214, Array) #1 [internal function]: AutomateController->getDestroy() #2 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(138): call_user_func_array(Array, Array) #3 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('getDestroy', Array) #4 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Router.php(985): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'getDestroy', Array) #5 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}() #6 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Route.php(80): call_user_func_array(Object(Closure), Array) #7 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Route.php(47): Illuminate\Routing\Route->callCallable() #8 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request)) #9 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #10 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #11 C:\xampp\htdocs\histogram\public\index.php(49): Illuminate\Foundation\Application->run() #12 {main} [] []
[2015-04-15 13:28:36] log.ERROR: exception 'ErrorException' with message 'Trying to get property of non-object' in C:\xampp\htdocs\histogram\app\controllers\AutomateController.php:214 Stack trace: #0 C:\xampp\htdocs\histogram\app\controllers\AutomateController.php(214): Illuminate\Exception\Handler->handleError(8, 'Trying to get p...', 'C:\\xampp\\htdocs...', 214, Array) #1 [internal function]: AutomateController->getDestroy() #2 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(138): call_user_func_array(Array, Array) #3 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('getDestroy', Array) #4 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Router.php(985): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'getDestroy', Array) #5 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}() #6 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Route.php(80): call_user_func_array(Object(Closure), Array) #7 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Route.php(47): Illuminate\Routing\Route->callCallable() #8 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request)) #9 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #10 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #11 C:\xampp\htdocs\histogram\public\index.php(49): Illuminate\Foundation\Application->run() #12 {main} [] []
[2015-04-15 13:28:39] log.ERROR: exception 'ErrorException' with message 'Trying to get property of non-object' in C:\xampp\htdocs\histogram\app\controllers\AutomateController.php:198 Stack trace: #0 C:\xampp\htdocs\histogram\app\controllers\AutomateController.php(198): Illuminate\Exception\Handler->handleError(8, 'Trying to get p...', 'C:\\xampp\\htdocs...', 198, Array) #1 [internal function]: AutomateController->getDelete('PJtpc-XT9c') #2 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(138): call_user_func_array(Array, Array) #3 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('getDelete', Array) #4 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Router.php(985): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'getDelete', Array) #5 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}('PJtpc-XT9c') #6 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Route.php(80): call_user_func_array(Object(Closure), Array) #7 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Route.php(47): Illuminate\Routing\Route->callCallable() #8 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request)) #9 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #10 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #11 C:\xampp\htdocs\histogram\public\index.php(49): Illuminate\Foundation\Application->run() #12 {main} [] []
[2015-04-15 13:28:50] log.ERROR: exception 'ErrorException' with message 'Trying to get property of non-object' in C:\xampp\htdocs\histogram\app\controllers\AutomateController.php:214 Stack trace: #0 C:\xampp\htdocs\histogram\app\controllers\AutomateController.php(214): Illuminate\Exception\Handler->handleError(8, 'Trying to get p...', 'C:\\xampp\\htdocs...', 214, Array) #1 [internal function]: AutomateController->getDestroy() #2 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(138): call_user_func_array(Array, Array) #3 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('getDestroy', Array) #4 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Router.php(985): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'getDestroy', Array) #5 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}() #6 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Route.php(80): call_user_func_array(Object(Closure), Array) #7 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Route.php(47): Illuminate\Routing\Route->callCallable() #8 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request)) #9 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #10 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #11 C:\xampp\htdocs\histogram\public\index.php(49): Illuminate\Foundation\Application->run() #12 {main} [] []
[2015-04-15 13:29:00] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Router.php:1429 Stack trace: #0 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1050): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 C:\xampp\htdocs\histogram\public\index.php(49): Illuminate\Foundation\Application->run() #5 {main} [] []
[2015-04-15 13:29:22] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Router.php:1429 Stack trace: #0 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1050): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 C:\xampp\htdocs\histogram\public\index.php(49): Illuminate\Foundation\Application->run() #5 {main} [] []
[2015-04-15 13:29:28] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Router.php:1429 Stack trace: #0 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1050): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 C:\xampp\htdocs\histogram\public\index.php(49): Illuminate\Foundation\Application->run() #5 {main} [] []
[2015-04-15 13:29:29] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Router.php:1429 Stack trace: #0 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1050): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 C:\xampp\htdocs\histogram\public\index.php(49): Illuminate\Foundation\Application->run() #5 {main} [] []
[2015-04-15 13:30:13] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Router.php:1429 Stack trace: #0 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1050): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 C:\xampp\htdocs\histogram\public\index.php(49): Illuminate\Foundation\Application->run() #5 {main} [] []
[2015-04-15 13:30:22] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Router.php:1429 Stack trace: #0 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1050): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 C:\xampp\htdocs\histogram\public\index.php(49): Illuminate\Foundation\Application->run() #5 {main} [] []
[2015-04-15 13:40:21] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Router.php:1429 Stack trace: #0 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1050): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 C:\xampp\htdocs\histogram\public\index.php(49): Illuminate\Foundation\Application->run() #5 {main} [] []
[2015-04-15 13:40:21] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Router.php:1429 Stack trace: #0 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1050): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 C:\xampp\htdocs\histogram\public\index.php(49): Illuminate\Foundation\Application->run() #5 {main} [] []
[2015-04-15 13:40:32] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Router.php:1429 Stack trace: #0 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1050): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 C:\xampp\htdocs\histogram\public\index.php(49): Illuminate\Foundation\Application->run() #5 {main} [] []
[2015-04-15 13:41:00] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Router.php:1429 Stack trace: #0 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1050): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 C:\xampp\htdocs\histogram\public\index.php(49): Illuminate\Foundation\Application->run() #5 {main} [] []
[2015-04-15 13:41:02] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Router.php:1429 Stack trace: #0 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1050): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 C:\xampp\htdocs\histogram\public\index.php(49): Illuminate\Foundation\Application->run() #5 {main} [] []
[2015-04-15 13:41:09] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Router.php:1429 Stack trace: #0 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1050): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 C:\xampp\htdocs\histogram\public\index.php(49): Illuminate\Foundation\Application->run() #5 {main} [] []
[2015-04-15 13:41:51] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Router.php:1429 Stack trace: #0 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1050): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 C:\xampp\htdocs\histogram\public\index.php(49): Illuminate\Foundation\Application->run() #5 {main} [] []
[2015-04-15 19:10:38] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Router.php:1429 Stack trace: #0 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1050): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 C:\xampp\htdocs\histogram\public\index.php(49): Illuminate\Foundation\Application->run() #5 {main} [] []
[2015-04-15 19:10:38] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Router.php:1429 Stack trace: #0 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1050): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 C:\xampp\htdocs\histogram\public\index.php(49): Illuminate\Foundation\Application->run() #5 {main} [] []
[2015-04-15 19:10:40] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Router.php:1429 Stack trace: #0 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1050): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 C:\xampp\htdocs\histogram\public\index.php(49): Illuminate\Foundation\Application->run() #5 {main} [] []
[2015-04-15 19:10:48] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Router.php:1429 Stack trace: #0 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1050): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 C:\xampp\htdocs\histogram\public\index.php(49): Illuminate\Foundation\Application->run() #5 {main} [] []
[2015-04-15 19:10:52] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Router.php:1429 Stack trace: #0 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1050): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 C:\xampp\htdocs\histogram\public\index.php(49): Illuminate\Foundation\Application->run() #5 {main} [] []
[2015-04-15 19:11:00] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Router.php:1429 Stack trace: #0 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1050): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 C:\xampp\htdocs\histogram\public\index.php(49): Illuminate\Foundation\Application->run() #5 {main} [] []
[2015-04-15 19:11:05] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Router.php:1429 Stack trace: #0 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1050): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 C:\xampp\htdocs\histogram\public\index.php(49): Illuminate\Foundation\Application->run() #5 {main} [] []
[2015-04-15 19:11:18] log.ERROR: exception 'Intervention\Image\Exception\MissingDependencyException' with message 'PHP Fileinfo extension must be installed/enabled to use Intervention Image.' in C:\xampp\htdocs\histogram\vendor\intervention\image\src\Intervention\Image\ImageManager.php:123 Stack trace: #0 C:\xampp\htdocs\histogram\vendor\intervention\image\src\Intervention\Image\ImageManager.php(25): Intervention\Image\ImageManager->checkRequirements() #1 C:\xampp\htdocs\histogram\vendor\intervention\image\src\Intervention\Image\ImageServiceProviderLaravel4.php(97): Intervention\Image\ImageManager->__construct(Array) #2 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Container\Container.php(149): Intervention\Image\ImageServiceProviderLaravel4->Intervention\Image\{closure}(Object(Illuminate\Foundation\Application)) #3 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Container\Container.php(305): Illuminate\Container\Container->Illuminate\Container\{closure}(Object(Illuminate\Foundation\Application), Array) #4 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Container\Container.php(250): Illuminate\Container\Container->build(Object(Closure), Array) #5 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(480): Illuminate\Container\Container->make('image', Array) #6 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Container\Container.php(537): Illuminate\Foundation\Application->make('image') #7 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Support\Facades\Facade.php(144): Illuminate\Container\Container->offsetGet('image') #8 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Support\Facades\Facade.php(198): Illuminate\Support\Facades\Facade::resolveFacadeInstance('image') #9 C:\xampp\htdocs\histogram\app\controllers\FilesController.php(106): Illuminate\Support\Facades\Facade::__callStatic('make', Array) #10 C:\xampp\htdocs\histogram\app\controllers\FilesController.php(106): Intervention\Image\Facades\Image::make('C:\\xampp\\htdocs...') #11 [internal function]: FilesController->postUpload() #12 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(138): call_user_func_array(Array, Array) #13 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('postUpload', Array) #14 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Router.php(985): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'postUpload', Array) #15 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}() #16 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Route.php(80): call_user_func_array(Object(Closure), Array) #17 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Route.php(47): Illuminate\Routing\Route->callCallable() #18 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request)) #19 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #20 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #21 C:\xampp\htdocs\histogram\public\index.php(49): Illuminate\Foundation\Application->run() #22 {main} [] []
[2015-04-15 19:11:18] log.ERROR: exception 'Intervention\Image\Exception\MissingDependencyException' with message 'PHP Fileinfo extension must be installed/enabled to use Intervention Image.' in C:\xampp\htdocs\histogram\vendor\intervention\image\src\Intervention\Image\ImageManager.php:123 Stack trace: #0 C:\xampp\htdocs\histogram\vendor\intervention\image\src\Intervention\Image\ImageManager.php(25): Intervention\Image\ImageManager->checkRequirements() #1 C:\xampp\htdocs\histogram\vendor\intervention\image\src\Intervention\Image\ImageServiceProviderLaravel4.php(97): Intervention\Image\ImageManager->__construct(Array) #2 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Container\Container.php(149): Intervention\Image\ImageServiceProviderLaravel4->Intervention\Image\{closure}(Object(Illuminate\Foundation\Application)) #3 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Container\Container.php(305): Illuminate\Container\Container->Illuminate\Container\{closure}(Object(Illuminate\Foundation\Application), Array) #4 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Container\Container.php(250): Illuminate\Container\Container->build(Object(Closure), Array) #5 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(480): Illuminate\Container\Container->make('image', Array) #6 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Container\Container.php(537): Illuminate\Foundation\Application->make('image') #7 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Support\Facades\Facade.php(144): Illuminate\Container\Container->offsetGet('image') #8 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Support\Facades\Facade.php(198): Illuminate\Support\Facades\Facade::resolveFacadeInstance('image') #9 C:\xampp\htdocs\histogram\app\controllers\FilesController.php(106): Illuminate\Support\Facades\Facade::__callStatic('make', Array) #10 C:\xampp\htdocs\histogram\app\controllers\FilesController.php(106): Intervention\Image\Facades\Image::make('C:\\xampp\\htdocs...') #11 [internal function]: FilesController->postUpload() #12 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(138): call_user_func_array(Array, Array) #13 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('postUpload', Array) #14 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Router.php(985): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'postUpload', Array) #15 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}() #16 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Route.php(80): call_user_func_array(Object(Closure), Array) #17 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Route.php(47): Illuminate\Routing\Route->callCallable() #18 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request)) #19 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #20 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #21 C:\xampp\htdocs\histogram\public\index.php(49): Illuminate\Foundation\Application->run() #22 {main} [] []
[2015-04-15 19:11:18] log.ERROR: exception 'Intervention\Image\Exception\MissingDependencyException' with message 'PHP Fileinfo extension must be installed/enabled to use Intervention Image.' in C:\xampp\htdocs\histogram\vendor\intervention\image\src\Intervention\Image\ImageManager.php:123 Stack trace: #0 C:\xampp\htdocs\histogram\vendor\intervention\image\src\Intervention\Image\ImageManager.php(25): Intervention\Image\ImageManager->checkRequirements() #1 C:\xampp\htdocs\histogram\vendor\intervention\image\src\Intervention\Image\ImageServiceProviderLaravel4.php(97): Intervention\Image\ImageManager->__construct(Array) #2 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Container\Container.php(149): Intervention\Image\ImageServiceProviderLaravel4->Intervention\Image\{closure}(Object(Illuminate\Foundation\Application)) #3 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Container\Container.php(305): Illuminate\Container\Container->Illuminate\Container\{closure}(Object(Illuminate\Foundation\Application), Array) #4 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Container\Container.php(250): Illuminate\Container\Container->build(Object(Closure), Array) #5 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(480): Illuminate\Container\Container->make('image', Array) #6 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Container\Container.php(537): Illuminate\Foundation\Application->make('image') #7 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Support\Facades\Facade.php(144): Illuminate\Container\Container->offsetGet('image') #8 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Support\Facades\Facade.php(198): Illuminate\Support\Facades\Facade::resolveFacadeInstance('image') #9 C:\xampp\htdocs\histogram\app\controllers\FilesController.php(106): Illuminate\Support\Facades\Facade::__callStatic('make', Array) #10 C:\xampp\htdocs\histogram\app\controllers\FilesController.php(106): Intervention\Image\Facades\Image::make('C:\\xampp\\htdocs...') #11 [internal function]: FilesController->postUpload() #12 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(138): call_user_func_array(Array, Array) #13 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('postUpload', Array) #14 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Router.php(985): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'postUpload', Array) #15 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}() #16 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Route.php(80): call_user_func_array(Object(Closure), Array) #17 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Route.php(47): Illuminate\Routing\Route->callCallable() #18 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request)) #19 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #20 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #21 C:\xampp\htdocs\histogram\public\index.php(49): Illuminate\Foundation\Application->run() #22 {main} [] []
[2015-04-15 19:11:20] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Router.php:1429 Stack trace: #0 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1050): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 C:\xampp\htdocs\histogram\public\index.php(49): Illuminate\Foundation\Application->run() #5 {main} [] []
[2015-04-15 19:11:22] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Router.php:1429 Stack trace: #0 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1050): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 C:\xampp\htdocs\histogram\public\index.php(49): Illuminate\Foundation\Application->run() #5 {main} [] []
[2015-04-15 19:12:27] log.ERROR: exception 'ErrorException' with message 'Trying to get property of non-object' in C:\xampp\htdocs\histogram\app\controllers\ManualController.php:164 Stack trace: #0 C:\xampp\htdocs\histogram\app\controllers\ManualController.php(164): Illuminate\Exception\Handler->handleError(8, 'Trying to get p...', 'C:\\xampp\\htdocs...', 164, Array) #1 [internal function]: ManualController->postSave() #2 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(138): call_user_func_array(Array, Array) #3 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('postSave', Array) #4 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Router.php(985): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'postSave', Array) #5 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}() #6 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Route.php(80): call_user_func_array(Object(Closure), Array) #7 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Route.php(47): Illuminate\Routing\Route->callCallable() #8 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request)) #9 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #10 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #11 C:\xampp\htdocs\histogram\public\index.php(49): Illuminate\Foundation\Application->run() #12 {main} [] []
[2015-04-15 19:13:29] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Router.php:1429 Stack trace: #0 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1050): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 C:\xampp\htdocs\histogram\public\index.php(49): Illuminate\Foundation\Application->run() #5 {main} [] []
[2015-04-15 19:13:34] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Router.php:1429 Stack trace: #0 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1050): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 C:\xampp\htdocs\histogram\public\index.php(49): Illuminate\Foundation\Application->run() #5 {main} [] []
[2015-04-15 19:13:35] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Router.php:1429 Stack trace: #0 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1050): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 C:\xampp\htdocs\histogram\public\index.php(49): Illuminate\Foundation\Application->run() #5 {main} [] []
[2015-04-15 19:13:39] log.ERROR: exception 'Intervention\Image\Exception\MissingDependencyException' with message 'PHP Fileinfo extension must be installed/enabled to use Intervention Image.' in C:\xampp\htdocs\histogram\vendor\intervention\image\src\Intervention\Image\ImageManager.php:123 Stack trace: #0 C:\xampp\htdocs\histogram\vendor\intervention\image\src\Intervention\Image\ImageManager.php(25): Intervention\Image\ImageManager->checkRequirements() #1 C:\xampp\htdocs\histogram\vendor\intervention\image\src\Intervention\Image\ImageServiceProviderLaravel4.php(97): Intervention\Image\ImageManager->__construct(Array) #2 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Container\Container.php(149): Intervention\Image\ImageServiceProviderLaravel4->Intervention\Image\{closure}(Object(Illuminate\Foundation\Application)) #3 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Container\Container.php(305): Illuminate\Container\Container->Illuminate\Container\{closure}(Object(Illuminate\Foundation\Application), Array) #4 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Container\Container.php(250): Illuminate\Container\Container->build(Object(Closure), Array) #5 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(480): Illuminate\Container\Container->make('image', Array) #6 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Container\Container.php(537): Illuminate\Foundation\Application->make('image') #7 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Support\Facades\Facade.php(144): Illuminate\Container\Container->offsetGet('image') #8 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Support\Facades\Facade.php(198): Illuminate\Support\Facades\Facade::resolveFacadeInstance('image') #9 C:\xampp\htdocs\histogram\app\controllers\FilesController.php(106): Illuminate\Support\Facades\Facade::__callStatic('make', Array) #10 C:\xampp\htdocs\histogram\app\controllers\FilesController.php(106): Intervention\Image\Facades\Image::make('C:\\xampp\\htdocs...') #11 [internal function]: FilesController->postUpload() #12 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(138): call_user_func_array(Array, Array) #13 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('postUpload', Array) #14 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Router.php(985): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'postUpload', Array) #15 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}() #16 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Route.php(80): call_user_func_array(Object(Closure), Array) #17 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Route.php(47): Illuminate\Routing\Route->callCallable() #18 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request)) #19 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #20 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #21 C:\xampp\htdocs\histogram\public\index.php(49): Illuminate\Foundation\Application->run() #22 {main} [] []
[2015-04-15 19:13:41] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Router.php:1429 Stack trace: #0 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1050): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 C:\xampp\htdocs\histogram\public\index.php(49): Illuminate\Foundation\Application->run() #5 {main} [] []
[2015-04-15 19:13:44] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Router.php:1429 Stack trace: #0 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1050): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 C:\xampp\htdocs\histogram\public\index.php(49): Illuminate\Foundation\Application->run() #5 {main} [] []
[2015-04-15 19:13:51] log.ERROR: exception 'ErrorException' with message 'Undefined index: x' in C:\xampp\htdocs\histogram\app\storage\views\a4145cdd75e745c280a02ce308271d68:97 Stack trace: #0 C:\xampp\htdocs\histogram\app\storage\views\a4145cdd75e745c280a02ce308271d68(97): Illuminate\Exception\Handler->handleError(8, 'Undefined index...', 'C:\\xampp\\htdocs...', 97, Array) #1 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\View\Engines\PhpEngine.php(38): include('C:\\xampp\\htdocs...') #2 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\View\Engines\CompilerEngine.php(45): Illuminate\View\Engines\PhpEngine->evaluatePath('C:\\xampp\\htdocs...', Array) #3 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\View\View.php(100): Illuminate\View\Engines\CompilerEngine->get('C:\\xampp\\htdocs...', Array) #4 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\View\View.php(81): Illuminate\View\View->getContents() #5 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Http\Response.php(70): Illuminate\View\View->render() #6 C:\xampp\htdocs\histogram\vendor\symfony\http-foundation\Symfony\Component\HttpFoundation\Response.php(141): Illuminate\Http\Response->setContent(Object(Illuminate\View\View)) #7 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1414): Symfony\Component\HttpFoundation\Response->__construct(Object(Illuminate\View\View)) #8 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(156): Illuminate\Routing\Router->prepare(Object(Illuminate\View\View), Object(Illuminate\Http\Request)) #9 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(126): Illuminate\Routing\Controllers\Controller->processResponse(Object(Illuminate\Routing\Router), 'postSave', Object(Illuminate\View\View)) #10 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Router.php(985): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'postSave', Array) #11 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}() #12 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Route.php(80): call_user_func_array(Object(Closure), Array) #13 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Route.php(47): Illuminate\Routing\Route->callCallable() #14 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request)) #15 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #16 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #17 C:\xampp\htdocs\histogram\public\index.php(49): Illuminate\Foundation\Application->run() #18 {main} [] []
[2015-04-15 19:18:56] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Router.php:1429 Stack trace: #0 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1050): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 C:\xampp\htdocs\histogram\public\index.php(49): Illuminate\Foundation\Application->run() #5 {main} [] []
[2015-04-15 19:18:56] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Router.php:1429 Stack trace: #0 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1050): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 C:\xampp\htdocs\histogram\public\index.php(49): Illuminate\Foundation\Application->run() #5 {main} [] []
[2015-04-15 19:18:57] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Router.php:1429 Stack trace: #0 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1050): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 C:\xampp\htdocs\histogram\public\index.php(49): Illuminate\Foundation\Application->run() #5 {main} [] []
[2015-04-15 19:19:03] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Router.php:1429 Stack trace: #0 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1050): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 C:\xampp\htdocs\histogram\public\index.php(49): Illuminate\Foundation\Application->run() #5 {main} [] []
[2015-04-15 19:19:06] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Router.php:1429 Stack trace: #0 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1050): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 C:\xampp\htdocs\histogram\public\index.php(49): Illuminate\Foundation\Application->run() #5 {main} [] []
[2015-04-15 19:19:08] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Router.php:1429 Stack trace: #0 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1050): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 C:\xampp\htdocs\histogram\public\index.php(49): Illuminate\Foundation\Application->run() #5 {main} [] []
[2015-04-15 19:19:11] log.ERROR: exception 'Intervention\Image\Exception\MissingDependencyException' with message 'PHP Fileinfo extension must be installed/enabled to use Intervention Image.' in C:\xampp\htdocs\histogram\vendor\intervention\image\src\Intervention\Image\ImageManager.php:123 Stack trace: #0 C:\xampp\htdocs\histogram\vendor\intervention\image\src\Intervention\Image\ImageManager.php(25): Intervention\Image\ImageManager->checkRequirements() #1 C:\xampp\htdocs\histogram\vendor\intervention\image\src\Intervention\Image\ImageServiceProviderLaravel4.php(97): Intervention\Image\ImageManager->__construct(Array) #2 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Container\Container.php(149): Intervention\Image\ImageServiceProviderLaravel4->Intervention\Image\{closure}(Object(Illuminate\Foundation\Application)) #3 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Container\Container.php(305): Illuminate\Container\Container->Illuminate\Container\{closure}(Object(Illuminate\Foundation\Application), Array) #4 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Container\Container.php(250): Illuminate\Container\Container->build(Object(Closure), Array) #5 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(480): Illuminate\Container\Container->make('image', Array) #6 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Container\Container.php(537): Illuminate\Foundation\Application->make('image') #7 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Support\Facades\Facade.php(144): Illuminate\Container\Container->offsetGet('image') #8 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Support\Facades\Facade.php(198): Illuminate\Support\Facades\Facade::resolveFacadeInstance('image') #9 C:\xampp\htdocs\histogram\app\controllers\FilesController.php(106): Illuminate\Support\Facades\Facade::__callStatic('make', Array) #10 C:\xampp\htdocs\histogram\app\controllers\FilesController.php(106): Intervention\Image\Facades\Image::make('C:\\xampp\\htdocs...') #11 [internal function]: FilesController->postUpload() #12 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(138): call_user_func_array(Array, Array) #13 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('postUpload', Array) #14 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Router.php(985): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'postUpload', Array) #15 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}() #16 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Route.php(80): call_user_func_array(Object(Closure), Array) #17 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Route.php(47): Illuminate\Routing\Route->callCallable() #18 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request)) #19 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #20 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #21 C:\xampp\htdocs\histogram\public\index.php(49): Illuminate\Foundation\Application->run() #22 {main} [] []
[2015-04-15 19:19:13] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Router.php:1429 Stack trace: #0 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1050): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 C:\xampp\htdocs\histogram\public\index.php(49): Illuminate\Foundation\Application->run() #5 {main} [] []
[2015-04-15 19:19:15] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Router.php:1429 Stack trace: #0 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1050): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 C:\xampp\htdocs\histogram\public\index.php(49): Illuminate\Foundation\Application->run() #5 {main} [] []
[2015-04-15 19:19:30] log.ERROR: exception 'ErrorException' with message 'Trying to get property of non-object' in C:\xampp\htdocs\histogram\app\controllers\ManualController.php:164 Stack trace: #0 C:\xampp\htdocs\histogram\app\controllers\ManualController.php(164): Illuminate\Exception\Handler->handleError(8, 'Trying to get p...', 'C:\\xampp\\htdocs...', 164, Array) #1 [internal function]: ManualController->postSave() #2 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(138): call_user_func_array(Array, Array) #3 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('postSave', Array) #4 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Router.php(985): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'postSave', Array) #5 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}() #6 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Route.php(80): call_user_func_array(Object(Closure), Array) #7 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Route.php(47): Illuminate\Routing\Route->callCallable() #8 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request)) #9 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #10 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #11 C:\xampp\htdocs\histogram\public\index.php(49): Illuminate\Foundation\Application->run() #12 {main} [] []
[2015-04-15 19:25:45] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Router.php:1429 Stack trace: #0 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1050): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 C:\xampp\htdocs\histogram\public\index.php(49): Illuminate\Foundation\Application->run() #5 {main} [] []
[2015-04-15 19:25:48] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Router.php:1429 Stack trace: #0 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1050): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 C:\xampp\htdocs\histogram\public\index.php(49): Illuminate\Foundation\Application->run() #5 {main} [] []
[2015-04-15 19:25:52] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Router.php:1429 Stack trace: #0 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1050): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 C:\xampp\htdocs\histogram\public\index.php(49): Illuminate\Foundation\Application->run() #5 {main} [] []
[2015-04-15 19:25:55] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Router.php:1429 Stack trace: #0 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1050): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 C:\xampp\htdocs\histogram\public\index.php(49): Illuminate\Foundation\Application->run() #5 {main} [] []
[2015-04-15 19:26:00] log.ERROR: exception 'Intervention\Image\Exception\MissingDependencyException' with message 'PHP Fileinfo extension must be installed/enabled to use Intervention Image.' in C:\xampp\htdocs\histogram\vendor\intervention\image\src\Intervention\Image\ImageManager.php:123 Stack trace: #0 C:\xampp\htdocs\histogram\vendor\intervention\image\src\Intervention\Image\ImageManager.php(25): Intervention\Image\ImageManager->checkRequirements() #1 C:\xampp\htdocs\histogram\vendor\intervention\image\src\Intervention\Image\ImageServiceProviderLaravel4.php(97): Intervention\Image\ImageManager->__construct(Array) #2 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Container\Container.php(149): Intervention\Image\ImageServiceProviderLaravel4->Intervention\Image\{closure}(Object(Illuminate\Foundation\Application)) #3 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Container\Container.php(305): Illuminate\Container\Container->Illuminate\Container\{closure}(Object(Illuminate\Foundation\Application), Array) #4 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Container\Container.php(250): Illuminate\Container\Container->build(Object(Closure), Array) #5 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(480): Illuminate\Container\Container->make('image', Array) #6 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Container\Container.php(537): Illuminate\Foundation\Application->make('image') #7 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Support\Facades\Facade.php(144): Illuminate\Container\Container->offsetGet('image') #8 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Support\Facades\Facade.php(198): Illuminate\Support\Facades\Facade::resolveFacadeInstance('image') #9 C:\xampp\htdocs\histogram\app\controllers\FilesController.php(106): Illuminate\Support\Facades\Facade::__callStatic('make', Array) #10 C:\xampp\htdocs\histogram\app\controllers\FilesController.php(106): Intervention\Image\Facades\Image::make('C:\\xampp\\htdocs...') #11 [internal function]: FilesController->postUpload() #12 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(138): call_user_func_array(Array, Array) #13 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('postUpload', Array) #14 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Router.php(985): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'postUpload', Array) #15 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}() #16 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Route.php(80): call_user_func_array(Object(Closure), Array) #17 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Route.php(47): Illuminate\Routing\Route->callCallable() #18 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request)) #19 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #20 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #21 C:\xampp\htdocs\histogram\public\index.php(49): Illuminate\Foundation\Application->run() #22 {main} [] []
[2015-04-15 19:26:01] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Router.php:1429 Stack trace: #0 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1050): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 C:\xampp\htdocs\histogram\public\index.php(49): Illuminate\Foundation\Application->run() #5 {main} [] []
[2015-04-15 19:26:03] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Router.php:1429 Stack trace: #0 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1050): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 C:\xampp\htdocs\histogram\public\index.php(49): Illuminate\Foundation\Application->run() #5 {main} [] []
[2015-04-15 19:26:14] log.ERROR: exception 'ErrorException' with message 'Trying to get property of non-object' in C:\xampp\htdocs\histogram\app\controllers\ManualController.php:164 Stack trace: #0 C:\xampp\htdocs\histogram\app\controllers\ManualController.php(164): Illuminate\Exception\Handler->handleError(8, 'Trying to get p...', 'C:\\xampp\\htdocs...', 164, Array) #1 [internal function]: ManualController->postSave() #2 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(138): call_user_func_array(Array, Array) #3 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('postSave', Array) #4 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Router.php(985): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'postSave', Array) #5 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}() #6 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Route.php(80): call_user_func_array(Object(Closure), Array) #7 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Route.php(47): Illuminate\Routing\Route->callCallable() #8 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request)) #9 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #10 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #11 C:\xampp\htdocs\histogram\public\index.php(49): Illuminate\Foundation\Application->run() #12 {main} [] []
[2015-04-15 19:27:22] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Router.php:1429 Stack trace: #0 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1050): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 C:\xampp\htdocs\histogram\public\index.php(49): Illuminate\Foundation\Application->run() #5 {main} [] []
[2015-04-15 19:27:25] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Router.php:1429 Stack trace: #0 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1050): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 C:\xampp\htdocs\histogram\public\index.php(49): Illuminate\Foundation\Application->run() #5 {main} [] []
[2015-04-15 19:27:28] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Router.php:1429 Stack trace: #0 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1050): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 C:\xampp\htdocs\histogram\public\index.php(49): Illuminate\Foundation\Application->run() #5 {main} [] []
[2015-04-15 19:27:31] log.ERROR: exception 'Intervention\Image\Exception\MissingDependencyException' with message 'PHP Fileinfo extension must be installed/enabled to use Intervention Image.' in C:\xampp\htdocs\histogram\vendor\intervention\image\src\Intervention\Image\ImageManager.php:123 Stack trace: #0 C:\xampp\htdocs\histogram\vendor\intervention\image\src\Intervention\Image\ImageManager.php(25): Intervention\Image\ImageManager->checkRequirements() #1 C:\xampp\htdocs\histogram\vendor\intervention\image\src\Intervention\Image\ImageServiceProviderLaravel4.php(97): Intervention\Image\ImageManager->__construct(Array) #2 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Container\Container.php(149): Intervention\Image\ImageServiceProviderLaravel4->Intervention\Image\{closure}(Object(Illuminate\Foundation\Application)) #3 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Container\Container.php(305): Illuminate\Container\Container->Illuminate\Container\{closure}(Object(Illuminate\Foundation\Application), Array) #4 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Container\Container.php(250): Illuminate\Container\Container->build(Object(Closure), Array) #5 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(480): Illuminate\Container\Container->make('image', Array) #6 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Container\Container.php(537): Illuminate\Foundation\Application->make('image') #7 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Support\Facades\Facade.php(144): Illuminate\Container\Container->offsetGet('image') #8 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Support\Facades\Facade.php(198): Illuminate\Support\Facades\Facade::resolveFacadeInstance('image') #9 C:\xampp\htdocs\histogram\app\controllers\FilesController.php(106): Illuminate\Support\Facades\Facade::__callStatic('make', Array) #10 C:\xampp\htdocs\histogram\app\controllers\FilesController.php(106): Intervention\Image\Facades\Image::make('C:\\xampp\\htdocs...') #11 [internal function]: FilesController->postUpload() #12 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(138): call_user_func_array(Array, Array) #13 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('postUpload', Array) #14 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Router.php(985): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'postUpload', Array) #15 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}() #16 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Route.php(80): call_user_func_array(Object(Closure), Array) #17 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Route.php(47): Illuminate\Routing\Route->callCallable() #18 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request)) #19 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #20 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #21 C:\xampp\htdocs\histogram\public\index.php(49): Illuminate\Foundation\Application->run() #22 {main} [] []
[2015-04-15 19:27:33] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Router.php:1429 Stack trace: #0 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1050): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 C:\xampp\htdocs\histogram\public\index.php(49): Illuminate\Foundation\Application->run() #5 {main} [] []
[2015-04-15 19:27:35] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Router.php:1429 Stack trace: #0 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1050): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 C:\xampp\htdocs\histogram\public\index.php(49): Illuminate\Foundation\Application->run() #5 {main} [] []
[2015-04-15 19:27:46] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Router.php:1429 Stack trace: #0 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1050): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 C:\xampp\htdocs\histogram\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 C:\xampp\htdocs\histogram\public\index.php(49): Illuminate\Foundation\Application->run() #5 {main} [] []
