[2015-02-11 12:43:50] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Routing/Router.php:1429 Stack trace: #0 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1050): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 /opt/lampp/htdocs/histogram/public/index.php(49): Illuminate\Foundation\Application->run() #5 {main} [] []
[2015-02-11 12:43:51] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Routing/Router.php:1429 Stack trace: #0 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1050): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 /opt/lampp/htdocs/histogram/public/index.php(49): Illuminate\Foundation\Application->run() #5 {main} [] []
[2015-02-11 12:43:51] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Routing/Router.php:1429 Stack trace: #0 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1050): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 /opt/lampp/htdocs/histogram/public/index.php(49): Illuminate\Foundation\Application->run() #5 {main} [] []
[2015-02-11 12:43:51] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Routing/Router.php:1429 Stack trace: #0 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1050): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 /opt/lampp/htdocs/histogram/public/index.php(49): Illuminate\Foundation\Application->run() #5 {main} [] []
[2015-02-11 12:43:51] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Routing/Router.php:1429 Stack trace: #0 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1050): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 /opt/lampp/htdocs/histogram/public/index.php(49): Illuminate\Foundation\Application->run() #5 {main} [] []
[2015-02-11 12:43:58] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Routing/Router.php:1429 Stack trace: #0 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1050): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 /opt/lampp/htdocs/histogram/public/index.php(49): Illuminate\Foundation\Application->run() #5 {main} [] []
[2015-02-11 12:43:58] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Routing/Router.php:1429 Stack trace: #0 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1050): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 /opt/lampp/htdocs/histogram/public/index.php(49): Illuminate\Foundation\Application->run() #5 {main} [] []
[2015-02-11 12:43:58] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Routing/Router.php:1429 Stack trace: #0 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1050): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 /opt/lampp/htdocs/histogram/public/index.php(49): Illuminate\Foundation\Application->run() #5 {main} [] []
[2015-02-11 12:43:58] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Routing/Router.php:1429 Stack trace: #0 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1050): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 /opt/lampp/htdocs/histogram/public/index.php(49): Illuminate\Foundation\Application->run() #5 {main} [] []
[2015-02-11 12:43:58] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Routing/Router.php:1429 Stack trace: #0 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1050): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 /opt/lampp/htdocs/histogram/public/index.php(49): Illuminate\Foundation\Application->run() #5 {main} [] []
[2015-02-11 13:34:49] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Routing/Router.php:1429 Stack trace: #0 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1050): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 /opt/lampp/htdocs/histogram/public/index.php(49): Illuminate\Foundation\Application->run() #5 {main} [] []
[2015-02-11 13:34:49] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Routing/Router.php:1429 Stack trace: #0 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1050): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 /opt/lampp/htdocs/histogram/public/index.php(49): Illuminate\Foundation\Application->run() #5 {main} [] []
[2015-02-11 13:34:49] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Routing/Router.php:1429 Stack trace: #0 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1050): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 /opt/lampp/htdocs/histogram/public/index.php(49): Illuminate\Foundation\Application->run() #5 {main} [] []
[2015-02-11 13:34:50] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Routing/Router.php:1429 Stack trace: #0 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1050): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 /opt/lampp/htdocs/histogram/public/index.php(49): Illuminate\Foundation\Application->run() #5 {main} [] []
[2015-02-11 13:34:50] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Routing/Router.php:1429 Stack trace: #0 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1050): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 /opt/lampp/htdocs/histogram/public/index.php(49): Illuminate\Foundation\Application->run() #5 {main} [] []
[2015-02-11 13:36:23] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Routing/Router.php:1429 Stack trace: #0 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1050): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 /opt/lampp/htdocs/histogram/public/index.php(49): Illuminate\Foundation\Application->run() #5 {main} [] []
[2015-02-11 13:36:23] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Routing/Router.php:1429 Stack trace: #0 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1050): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 /opt/lampp/htdocs/histogram/public/index.php(49): Illuminate\Foundation\Application->run() #5 {main} [] []
[2015-02-11 13:36:23] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Routing/Router.php:1429 Stack trace: #0 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1050): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 /opt/lampp/htdocs/histogram/public/index.php(49): Illuminate\Foundation\Application->run() #5 {main} [] []
[2015-02-11 13:36:24] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Routing/Router.php:1429 Stack trace: #0 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1050): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 /opt/lampp/htdocs/histogram/public/index.php(49): Illuminate\Foundation\Application->run() #5 {main} [] []
[2015-02-11 13:36:24] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Routing/Router.php:1429 Stack trace: #0 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1050): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 /opt/lampp/htdocs/histogram/public/index.php(49): Illuminate\Foundation\Application->run() #5 {main} [] []
[2015-02-11 13:37:21] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Routing/Router.php:1429 Stack trace: #0 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1050): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 /opt/lampp/htdocs/histogram/public/index.php(49): Illuminate\Foundation\Application->run() #5 {main} [] []
[2015-02-11 13:37:21] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Routing/Router.php:1429 Stack trace: #0 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1050): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 /opt/lampp/htdocs/histogram/public/index.php(49): Illuminate\Foundation\Application->run() #5 {main} [] []
[2015-02-11 13:37:21] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Routing/Router.php:1429 Stack trace: #0 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1050): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 /opt/lampp/htdocs/histogram/public/index.php(49): Illuminate\Foundation\Application->run() #5 {main} [] []
[2015-02-11 13:37:21] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Routing/Router.php:1429 Stack trace: #0 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1050): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 /opt/lampp/htdocs/histogram/public/index.php(49): Illuminate\Foundation\Application->run() #5 {main} [] []
[2015-02-11 13:37:21] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Routing/Router.php:1429 Stack trace: #0 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1050): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 /opt/lampp/htdocs/histogram/public/index.php(49): Illuminate\Foundation\Application->run() #5 {main} [] []
[2015-02-11 13:37:25] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Routing/Router.php:1429 Stack trace: #0 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1050): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 /opt/lampp/htdocs/histogram/public/index.php(49): Illuminate\Foundation\Application->run() #5 {main} [] []
[2015-02-11 13:37:25] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Routing/Router.php:1429 Stack trace: #0 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1050): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 /opt/lampp/htdocs/histogram/public/index.php(49): Illuminate\Foundation\Application->run() #5 {main} [] []
[2015-02-11 13:37:25] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Routing/Router.php:1429 Stack trace: #0 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1050): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 /opt/lampp/htdocs/histogram/public/index.php(49): Illuminate\Foundation\Application->run() #5 {main} [] []
[2015-02-11 13:37:25] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Routing/Router.php:1429 Stack trace: #0 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1050): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 /opt/lampp/htdocs/histogram/public/index.php(49): Illuminate\Foundation\Application->run() #5 {main} [] []
[2015-02-11 13:37:25] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Routing/Router.php:1429 Stack trace: #0 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1050): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 /opt/lampp/htdocs/histogram/public/index.php(49): Illuminate\Foundation\Application->run() #5 {main} [] []
[2015-02-11 13:37:32] log.ERROR: exception 'Intervention\Image\Exception\NotReadableException' with message 'Unable to read image from file (/opt/lampp/htdocs/histogram/public/uploads/input_oke.xls).' in /opt/lampp/htdocs/histogram/vendor/intervention/image/src/Intervention/Image/Gd/Decoder.php:21 Stack trace: #0 /opt/lampp/htdocs/histogram/vendor/intervention/image/src/Intervention/Image/AbstractDecoder.php(248): Intervention\Image\Gd\Decoder->initFromPath('/opt/lampp/htdo...') #1 /opt/lampp/htdocs/histogram/vendor/intervention/image/src/Intervention/Image/AbstractDriver.php(64): Intervention\Image\AbstractDecoder->init('/opt/lampp/htdo...') #2 /opt/lampp/htdocs/histogram/vendor/intervention/image/src/Intervention/Image/ImageManager.php(50): Intervention\Image\AbstractDriver->init('/opt/lampp/htdo...') #3 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(206): Intervention\Image\ImageManager->make('/opt/lampp/htdo...') #4 /opt/lampp/htdocs/histogram/app/controllers/FileController.php(29): Illuminate\Support\Facades\Facade::__callStatic('make', Array) #5 /opt/lampp/htdocs/histogram/app/controllers/FileController.php(29): Intervention\Image\Facades\Image::make('/opt/lampp/htdo...') #6 [internal function]: FileController->postUpload() #7 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(138): call_user_func_array(Array, Array) #8 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('postUpload', Array) #9 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Routing/Router.php(985): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'postUpload', Array) #10 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}() #11 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Routing/Route.php(80): call_user_func_array(Object(Closure), Array) #12 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Routing/Route.php(47): Illuminate\Routing\Route->callCallable() #13 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request)) #14 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #15 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #16 /opt/lampp/htdocs/histogram/public/index.php(49): Illuminate\Foundation\Application->run() #17 {main} [] []
[2015-02-11 13:37:34] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Routing/Router.php:1429 Stack trace: #0 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1050): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 /opt/lampp/htdocs/histogram/public/index.php(49): Illuminate\Foundation\Application->run() #5 {main} [] []
[2015-02-11 13:37:34] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Routing/Router.php:1429 Stack trace: #0 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1050): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 /opt/lampp/htdocs/histogram/public/index.php(49): Illuminate\Foundation\Application->run() #5 {main} [] []
[2015-02-11 13:37:34] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Routing/Router.php:1429 Stack trace: #0 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1050): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 /opt/lampp/htdocs/histogram/public/index.php(49): Illuminate\Foundation\Application->run() #5 {main} [] []
[2015-02-11 13:37:34] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Routing/Router.php:1429 Stack trace: #0 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1050): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 /opt/lampp/htdocs/histogram/public/index.php(49): Illuminate\Foundation\Application->run() #5 {main} [] []
[2015-02-11 13:37:34] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Routing/Router.php:1429 Stack trace: #0 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1050): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 /opt/lampp/htdocs/histogram/public/index.php(49): Illuminate\Foundation\Application->run() #5 {main} [] []
[2015-02-11 13:37:37] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Routing/Router.php:1429 Stack trace: #0 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1050): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 /opt/lampp/htdocs/histogram/public/index.php(49): Illuminate\Foundation\Application->run() #5 {main} [] []
[2015-02-11 13:37:38] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Routing/Router.php:1429 Stack trace: #0 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1050): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 /opt/lampp/htdocs/histogram/public/index.php(49): Illuminate\Foundation\Application->run() #5 {main} [] []
[2015-02-11 13:37:38] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Routing/Router.php:1429 Stack trace: #0 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1050): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 /opt/lampp/htdocs/histogram/public/index.php(49): Illuminate\Foundation\Application->run() #5 {main} [] []
[2015-02-11 13:37:38] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Routing/Router.php:1429 Stack trace: #0 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1050): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 /opt/lampp/htdocs/histogram/public/index.php(49): Illuminate\Foundation\Application->run() #5 {main} [] []
[2015-02-11 13:37:38] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Routing/Router.php:1429 Stack trace: #0 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1050): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 /opt/lampp/htdocs/histogram/public/index.php(49): Illuminate\Foundation\Application->run() #5 {main} [] []
[2015-02-11 13:37:41] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Routing/Router.php:1429 Stack trace: #0 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1050): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 /opt/lampp/htdocs/histogram/public/index.php(49): Illuminate\Foundation\Application->run() #5 {main} [] []
[2015-02-11 13:37:41] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Routing/Router.php:1429 Stack trace: #0 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1050): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 /opt/lampp/htdocs/histogram/public/index.php(49): Illuminate\Foundation\Application->run() #5 {main} [] []
[2015-02-11 13:37:41] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Routing/Router.php:1429 Stack trace: #0 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1050): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 /opt/lampp/htdocs/histogram/public/index.php(49): Illuminate\Foundation\Application->run() #5 {main} [] []
[2015-02-11 13:37:41] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Routing/Router.php:1429 Stack trace: #0 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1050): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 /opt/lampp/htdocs/histogram/public/index.php(49): Illuminate\Foundation\Application->run() #5 {main} [] []
[2015-02-11 13:37:41] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Routing/Router.php:1429 Stack trace: #0 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1050): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 /opt/lampp/htdocs/histogram/public/index.php(49): Illuminate\Foundation\Application->run() #5 {main} [] []
[2015-02-11 13:38:01] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Routing/Router.php:1429 Stack trace: #0 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1050): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 /opt/lampp/htdocs/histogram/public/index.php(49): Illuminate\Foundation\Application->run() #5 {main} [] []
[2015-02-11 13:38:01] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Routing/Router.php:1429 Stack trace: #0 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1050): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 /opt/lampp/htdocs/histogram/public/index.php(49): Illuminate\Foundation\Application->run() #5 {main} [] []
[2015-02-11 13:38:02] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Routing/Router.php:1429 Stack trace: #0 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1050): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 /opt/lampp/htdocs/histogram/public/index.php(49): Illuminate\Foundation\Application->run() #5 {main} [] []
[2015-02-11 13:38:02] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Routing/Router.php:1429 Stack trace: #0 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1050): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 /opt/lampp/htdocs/histogram/public/index.php(49): Illuminate\Foundation\Application->run() #5 {main} [] []
[2015-02-11 13:38:02] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Routing/Router.php:1429 Stack trace: #0 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1050): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 /opt/lampp/htdocs/histogram/public/index.php(49): Illuminate\Foundation\Application->run() #5 {main} [] []
[2015-02-11 13:38:26] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Routing/Router.php:1429 Stack trace: #0 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1050): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 /opt/lampp/htdocs/histogram/public/index.php(49): Illuminate\Foundation\Application->run() #5 {main} [] []
[2015-02-11 13:38:26] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Routing/Router.php:1429 Stack trace: #0 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1050): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 /opt/lampp/htdocs/histogram/public/index.php(49): Illuminate\Foundation\Application->run() #5 {main} [] []
[2015-02-11 13:38:27] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Routing/Router.php:1429 Stack trace: #0 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1050): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 /opt/lampp/htdocs/histogram/public/index.php(49): Illuminate\Foundation\Application->run() #5 {main} [] []
[2015-02-11 13:38:27] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Routing/Router.php:1429 Stack trace: #0 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1050): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 /opt/lampp/htdocs/histogram/public/index.php(49): Illuminate\Foundation\Application->run() #5 {main} [] []
[2015-02-11 13:38:27] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Routing/Router.php:1429 Stack trace: #0 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1050): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 /opt/lampp/htdocs/histogram/public/index.php(49): Illuminate\Foundation\Application->run() #5 {main} [] []
[2015-02-11 13:38:28] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Routing/Router.php:1429 Stack trace: #0 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1050): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 /opt/lampp/htdocs/histogram/public/index.php(49): Illuminate\Foundation\Application->run() #5 {main} [] []
[2015-02-11 13:38:28] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Routing/Router.php:1429 Stack trace: #0 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1050): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 /opt/lampp/htdocs/histogram/public/index.php(49): Illuminate\Foundation\Application->run() #5 {main} [] []
[2015-02-11 13:39:42] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Routing/Router.php:1429 Stack trace: #0 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1050): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 /opt/lampp/htdocs/histogram/public/index.php(49): Illuminate\Foundation\Application->run() #5 {main} [] []
[2015-02-11 13:39:42] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Routing/Router.php:1429 Stack trace: #0 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1050): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 /opt/lampp/htdocs/histogram/public/index.php(49): Illuminate\Foundation\Application->run() #5 {main} [] []
[2015-02-11 13:39:42] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Routing/Router.php:1429 Stack trace: #0 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1050): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 /opt/lampp/htdocs/histogram/public/index.php(49): Illuminate\Foundation\Application->run() #5 {main} [] []
[2015-02-11 13:39:42] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Routing/Router.php:1429 Stack trace: #0 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1050): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 /opt/lampp/htdocs/histogram/public/index.php(49): Illuminate\Foundation\Application->run() #5 {main} [] []
[2015-02-11 13:39:42] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Routing/Router.php:1429 Stack trace: #0 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1050): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 /opt/lampp/htdocs/histogram/public/index.php(49): Illuminate\Foundation\Application->run() #5 {main} [] []
[2015-02-11 13:39:45] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Routing/Router.php:1429 Stack trace: #0 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1050): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 /opt/lampp/htdocs/histogram/public/index.php(49): Illuminate\Foundation\Application->run() #5 {main} [] []
[2015-02-11 13:39:45] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Routing/Router.php:1429 Stack trace: #0 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1050): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 /opt/lampp/htdocs/histogram/public/index.php(49): Illuminate\Foundation\Application->run() #5 {main} [] []
[2015-02-11 13:39:45] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Routing/Router.php:1429 Stack trace: #0 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1050): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 /opt/lampp/htdocs/histogram/public/index.php(49): Illuminate\Foundation\Application->run() #5 {main} [] []
[2015-02-11 13:39:45] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Routing/Router.php:1429 Stack trace: #0 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1050): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 /opt/lampp/htdocs/histogram/public/index.php(49): Illuminate\Foundation\Application->run() #5 {main} [] []
[2015-02-11 13:39:45] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Routing/Router.php:1429 Stack trace: #0 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1050): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 /opt/lampp/htdocs/histogram/public/index.php(49): Illuminate\Foundation\Application->run() #5 {main} [] []
[2015-02-11 13:41:10] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Routing/Router.php:1429 Stack trace: #0 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1050): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 /opt/lampp/htdocs/histogram/public/index.php(49): Illuminate\Foundation\Application->run() #5 {main} [] []
[2015-02-11 13:41:10] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Routing/Router.php:1429 Stack trace: #0 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1050): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 /opt/lampp/htdocs/histogram/public/index.php(49): Illuminate\Foundation\Application->run() #5 {main} [] []
[2015-02-11 13:41:11] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Routing/Router.php:1429 Stack trace: #0 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1050): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 /opt/lampp/htdocs/histogram/public/index.php(49): Illuminate\Foundation\Application->run() #5 {main} [] []
[2015-02-11 13:41:11] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Routing/Router.php:1429 Stack trace: #0 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1050): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 /opt/lampp/htdocs/histogram/public/index.php(49): Illuminate\Foundation\Application->run() #5 {main} [] []
[2015-02-11 13:41:11] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Routing/Router.php:1429 Stack trace: #0 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1050): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 /opt/lampp/htdocs/histogram/public/index.php(49): Illuminate\Foundation\Application->run() #5 {main} [] []
[2015-02-11 13:41:14] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Routing/Router.php:1429 Stack trace: #0 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1050): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 /opt/lampp/htdocs/histogram/public/index.php(49): Illuminate\Foundation\Application->run() #5 {main} [] []
[2015-02-11 13:41:14] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Routing/Router.php:1429 Stack trace: #0 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1050): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 /opt/lampp/htdocs/histogram/public/index.php(49): Illuminate\Foundation\Application->run() #5 {main} [] []
[2015-02-11 13:41:14] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Routing/Router.php:1429 Stack trace: #0 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1050): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 /opt/lampp/htdocs/histogram/public/index.php(49): Illuminate\Foundation\Application->run() #5 {main} [] []
[2015-02-11 13:41:14] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Routing/Router.php:1429 Stack trace: #0 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1050): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 /opt/lampp/htdocs/histogram/public/index.php(49): Illuminate\Foundation\Application->run() #5 {main} [] []
[2015-02-11 13:41:14] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Routing/Router.php:1429 Stack trace: #0 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1050): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 /opt/lampp/htdocs/histogram/public/index.php(49): Illuminate\Foundation\Application->run() #5 {main} [] []
