[2015-02-16 21:54:58] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Routing/Router.php:1429 Stack trace: #0 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1050): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 /opt/lampp/htdocs/histogram/public/index.php(49): Illuminate\Foundation\Application->run() #5 {main} [] []
[2015-02-16 21:54:58] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Routing/Router.php:1429 Stack trace: #0 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1050): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 /opt/lampp/htdocs/histogram/public/index.php(49): Illuminate\Foundation\Application->run() #5 {main} [] []
[2015-02-16 21:54:58] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Routing/Router.php:1429 Stack trace: #0 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1050): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 /opt/lampp/htdocs/histogram/public/index.php(49): Illuminate\Foundation\Application->run() #5 {main} [] []
[2015-02-16 21:54:58] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Routing/Router.php:1429 Stack trace: #0 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1050): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 /opt/lampp/htdocs/histogram/public/index.php(49): Illuminate\Foundation\Application->run() #5 {main} [] []
[2015-02-16 21:54:58] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Routing/Router.php:1429 Stack trace: #0 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1050): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 /opt/lampp/htdocs/histogram/public/index.php(49): Illuminate\Foundation\Application->run() #5 {main} [] []
[2015-02-16 21:55:07] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Routing/Router.php:1429 Stack trace: #0 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1050): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 /opt/lampp/htdocs/histogram/public/index.php(49): Illuminate\Foundation\Application->run() #5 {main} [] []
[2015-02-16 21:55:07] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Routing/Router.php:1429 Stack trace: #0 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1050): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 /opt/lampp/htdocs/histogram/public/index.php(49): Illuminate\Foundation\Application->run() #5 {main} [] []
[2015-02-16 21:55:08] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Routing/Router.php:1429 Stack trace: #0 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1050): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 /opt/lampp/htdocs/histogram/public/index.php(49): Illuminate\Foundation\Application->run() #5 {main} [] []
[2015-02-16 21:55:08] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Routing/Router.php:1429 Stack trace: #0 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1050): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 /opt/lampp/htdocs/histogram/public/index.php(49): Illuminate\Foundation\Application->run() #5 {main} [] []
[2015-02-16 21:55:08] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Routing/Router.php:1429 Stack trace: #0 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1050): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 /opt/lampp/htdocs/histogram/public/index.php(49): Illuminate\Foundation\Application->run() #5 {main} [] []
[2015-02-16 21:55:11] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Routing/Router.php:1429 Stack trace: #0 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1050): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 /opt/lampp/htdocs/histogram/public/index.php(49): Illuminate\Foundation\Application->run() #5 {main} [] []
[2015-02-16 21:55:11] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Routing/Router.php:1429 Stack trace: #0 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1050): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 /opt/lampp/htdocs/histogram/public/index.php(49): Illuminate\Foundation\Application->run() #5 {main} [] []
[2015-02-16 21:55:11] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Routing/Router.php:1429 Stack trace: #0 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1050): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 /opt/lampp/htdocs/histogram/public/index.php(49): Illuminate\Foundation\Application->run() #5 {main} [] []
[2015-02-16 21:55:11] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Routing/Router.php:1429 Stack trace: #0 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1050): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 /opt/lampp/htdocs/histogram/public/index.php(49): Illuminate\Foundation\Application->run() #5 {main} [] []
[2015-02-16 21:55:11] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Routing/Router.php:1429 Stack trace: #0 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1050): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 /opt/lampp/htdocs/histogram/public/index.php(49): Illuminate\Foundation\Application->run() #5 {main} [] []
[2015-02-16 21:55:15] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Routing/Router.php:1429 Stack trace: #0 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1050): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 /opt/lampp/htdocs/histogram/public/index.php(49): Illuminate\Foundation\Application->run() #5 {main} [] []
[2015-02-16 21:55:15] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Routing/Router.php:1429 Stack trace: #0 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1050): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 /opt/lampp/htdocs/histogram/public/index.php(49): Illuminate\Foundation\Application->run() #5 {main} [] []
[2015-02-16 21:55:15] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Routing/Router.php:1429 Stack trace: #0 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1050): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 /opt/lampp/htdocs/histogram/public/index.php(49): Illuminate\Foundation\Application->run() #5 {main} [] []
[2015-02-16 21:55:16] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Routing/Router.php:1429 Stack trace: #0 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1050): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 /opt/lampp/htdocs/histogram/public/index.php(49): Illuminate\Foundation\Application->run() #5 {main} [] []
[2015-02-16 21:55:16] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Routing/Router.php:1429 Stack trace: #0 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1050): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 /opt/lampp/htdocs/histogram/public/index.php(49): Illuminate\Foundation\Application->run() #5 {main} [] []
[2015-02-16 21:55:16] log.ERROR: exception 'ErrorException' with message 'Undefined variable: range_type' in /opt/lampp/htdocs/histogram/app/storage/views/a2969355a09c202d9d21c8afc07679b3:94 Stack trace: #0 /opt/lampp/htdocs/histogram/app/storage/views/a2969355a09c202d9d21c8afc07679b3(94): Illuminate\Exception\Handler->handleError(8, 'Undefined varia...', '/opt/lampp/htdo...', 94, Array) #1 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/View/Engines/PhpEngine.php(38): include('/opt/lampp/htdo...') #2 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/View/Engines/CompilerEngine.php(45): Illuminate\View\Engines\PhpEngine->evaluatePath('/opt/lampp/htdo...', Array) #3 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/View/View.php(100): Illuminate\View\Engines\CompilerEngine->get('/opt/lampp/htdo...', Array) #4 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/View/View.php(81): Illuminate\View\View->getContents() #5 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Http/Response.php(70): Illuminate\View\View->render() #6 /opt/lampp/htdocs/histogram/vendor/symfony/http-foundation/Symfony/Component/HttpFoundation/Response.php(141): Illuminate\Http\Response->setContent(Object(Illuminate\View\View)) #7 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1414): Symfony\Component\HttpFoundation\Response->__construct(Object(Illuminate\View\View)) #8 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(156): Illuminate\Routing\Router->prepare(Object(Illuminate\View\View), Object(Illuminate\Http\Request)) #9 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Routing/Controllers/Controller.php(126): Illuminate\Routing\Controllers\Controller->processResponse(Object(Illuminate\Routing\Router), 'getIndex', Object(Illuminate\View\View)) #10 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Routing/Router.php(985): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'getIndex', Array) #11 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}() #12 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Routing/Route.php(80): call_user_func_array(Object(Closure), Array) #13 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Routing/Route.php(47): Illuminate\Routing\Route->callCallable() #14 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1016): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request)) #15 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #16 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #17 /opt/lampp/htdocs/histogram/public/index.php(49): Illuminate\Foundation\Application->run() #18 {main} [] []
[2015-02-16 21:55:21] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Routing/Router.php:1429 Stack trace: #0 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1050): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 /opt/lampp/htdocs/histogram/public/index.php(49): Illuminate\Foundation\Application->run() #5 {main} [] []
[2015-02-16 21:55:21] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Routing/Router.php:1429 Stack trace: #0 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1050): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 /opt/lampp/htdocs/histogram/public/index.php(49): Illuminate\Foundation\Application->run() #5 {main} [] []
[2015-02-16 21:55:21] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Routing/Router.php:1429 Stack trace: #0 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1050): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 /opt/lampp/htdocs/histogram/public/index.php(49): Illuminate\Foundation\Application->run() #5 {main} [] []
[2015-02-16 21:55:21] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Routing/Router.php:1429 Stack trace: #0 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1050): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 /opt/lampp/htdocs/histogram/public/index.php(49): Illuminate\Foundation\Application->run() #5 {main} [] []
[2015-02-16 21:55:21] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Routing/Router.php:1429 Stack trace: #0 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1050): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 /opt/lampp/htdocs/histogram/public/index.php(49): Illuminate\Foundation\Application->run() #5 {main} [] []
[2015-02-16 22:00:13] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Routing/Router.php:1429 Stack trace: #0 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1050): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 /opt/lampp/htdocs/histogram/public/index.php(49): Illuminate\Foundation\Application->run() #5 {main} [] []
[2015-02-16 22:00:13] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Routing/Router.php:1429 Stack trace: #0 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1050): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 /opt/lampp/htdocs/histogram/public/index.php(49): Illuminate\Foundation\Application->run() #5 {main} [] []
[2015-02-16 22:00:35] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Routing/Router.php:1429 Stack trace: #0 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1050): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 /opt/lampp/htdocs/histogram/public/index.php(49): Illuminate\Foundation\Application->run() #5 {main} [] []
[2015-02-16 22:00:50] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Routing/Router.php:1429 Stack trace: #0 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1050): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 /opt/lampp/htdocs/histogram/public/index.php(49): Illuminate\Foundation\Application->run() #5 {main} [] []
[2015-02-16 22:00:52] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Routing/Router.php:1429 Stack trace: #0 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1050): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 /opt/lampp/htdocs/histogram/public/index.php(49): Illuminate\Foundation\Application->run() #5 {main} [] []
[2015-02-16 22:00:55] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Routing/Router.php:1429 Stack trace: #0 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1050): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 /opt/lampp/htdocs/histogram/public/index.php(49): Illuminate\Foundation\Application->run() #5 {main} [] []
[2015-02-16 22:01:09] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Routing/Router.php:1429 Stack trace: #0 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1050): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 /opt/lampp/htdocs/histogram/public/index.php(49): Illuminate\Foundation\Application->run() #5 {main} [] []
[2015-02-16 22:01:10] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Routing/Router.php:1429 Stack trace: #0 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1050): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 /opt/lampp/htdocs/histogram/public/index.php(49): Illuminate\Foundation\Application->run() #5 {main} [] []
[2015-02-16 22:01:10] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Routing/Router.php:1429 Stack trace: #0 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1050): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 /opt/lampp/htdocs/histogram/public/index.php(49): Illuminate\Foundation\Application->run() #5 {main} [] []
[2015-02-16 22:02:24] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Routing/Router.php:1429 Stack trace: #0 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1050): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 /opt/lampp/htdocs/histogram/public/index.php(49): Illuminate\Foundation\Application->run() #5 {main} [] []
[2015-02-16 22:03:20] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Routing/Router.php:1429 Stack trace: #0 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1050): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 /opt/lampp/htdocs/histogram/public/index.php(49): Illuminate\Foundation\Application->run() #5 {main} [] []
[2015-02-16 22:03:23] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Routing/Router.php:1429 Stack trace: #0 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1050): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 /opt/lampp/htdocs/histogram/public/index.php(49): Illuminate\Foundation\Application->run() #5 {main} [] []
[2015-02-16 22:03:32] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Routing/Router.php:1429 Stack trace: #0 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1050): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 /opt/lampp/htdocs/histogram/public/index.php(49): Illuminate\Foundation\Application->run() #5 {main} [] []
[2015-02-16 22:03:33] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Routing/Router.php:1429 Stack trace: #0 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1050): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 /opt/lampp/htdocs/histogram/public/index.php(49): Illuminate\Foundation\Application->run() #5 {main} [] []
[2015-02-16 22:03:33] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Routing/Router.php:1429 Stack trace: #0 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1050): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 /opt/lampp/htdocs/histogram/public/index.php(49): Illuminate\Foundation\Application->run() #5 {main} [] []
[2015-02-16 22:03:48] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Routing/Router.php:1429 Stack trace: #0 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1050): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 /opt/lampp/htdocs/histogram/public/index.php(49): Illuminate\Foundation\Application->run() #5 {main} [] []
[2015-02-16 22:03:48] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Routing/Router.php:1429 Stack trace: #0 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1050): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 /opt/lampp/htdocs/histogram/public/index.php(49): Illuminate\Foundation\Application->run() #5 {main} [] []
[2015-02-16 22:03:48] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Routing/Router.php:1429 Stack trace: #0 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1050): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 /opt/lampp/htdocs/histogram/public/index.php(49): Illuminate\Foundation\Application->run() #5 {main} [] []
[2015-02-16 22:03:59] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Routing/Router.php:1429 Stack trace: #0 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1050): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 /opt/lampp/htdocs/histogram/public/index.php(49): Illuminate\Foundation\Application->run() #5 {main} [] []
[2015-02-16 22:04:00] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Routing/Router.php:1429 Stack trace: #0 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1050): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 /opt/lampp/htdocs/histogram/public/index.php(49): Illuminate\Foundation\Application->run() #5 {main} [] []
[2015-02-16 22:04:00] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Routing/Router.php:1429 Stack trace: #0 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1050): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException)) #1 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Routing/Router.php(1014): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request)) #2 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(576): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request)) #3 /opt/lampp/htdocs/histogram/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(552): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request)) #4 /opt/lampp/htdocs/histogram/public/index.php(49): Illuminate\Foundation\Application->run() #5 {main} [] []
